ticket:978 - check if user has correct permissions when starting/initializing rasdaman

diff --git a/bin/create_db.sh.in b/bin/create_db.sh.in
--- a/bin/create_db.sh.in
+++ b/bin/create_db.sh.in
@@ -108,7 +108,23 @@ fi
 
 # - rasdaman part
 
-echo -n "$PROG: rasdaman dictionnary initialization...\c"
+echo -n "$PROG: rasdaman dictionary initialization...\c"
+
+# - check if user has rights to create SQLite database
+if [ "$BASEDBMS" == "$BASEDBMS_SQLITE" ]; then
+  datadir=$(dirname "@dbconn@")
+  if [ ! -w "$datadir" ]
+  then
+    echo "$MYNAME: User $USER has no write permissions in $datadir, rasdaman database cannot be created." >&2
+    exit $RC_ERROR
+  fi
+  if [ ! -x "$datadir" ]
+  then
+    echo "$MYNAME: User $USER has no execute permissions in $datadir (and/or parent directories), rasdaman database cannot be created." >&2
+    exit $RC_ERROR
+  fi
+fi
+
 @bindir@rasdl -c --connect @dbconn@ && @bindir@rasdl -r $DEFINITION_FILE -i --connect @dbconn@
 if [[ $? != 0 ]]
 then
diff --git a/bin/start_rasdaman.sh.in b/bin/start_rasdaman.sh.in
--- a/bin/start_rasdaman.sh.in
+++ b/bin/start_rasdaman.sh.in
@@ -81,6 +81,13 @@ echo $MYNAME: starting rasdaman server complex...
 # here we want to put all log files
 cd @logdir@
 
+# check if we can actually write anything here
+if [ ! -w nohup.out ]
+then
+  echo "$MYNAME: User $USER has no write permissions in @logdir@, rasdaman cannot be started." >&2
+  exit $RC_ERROR
+fi
+
 # clear previous log file
 rm -f nohup.out
 
