ticket:1538 - remove boost.spirit dependency
Summary: we use boost.spirit to parse the rascontrol commands. This library poses several issues: we cannot compile rasdaman with boost v1.61-v1.64, compilation takes far more time and memory. The rascontrol commands are simply command-line options and using a special parsing library for "parsing" them is completely unnecessary. This patch reverts to the old method of reading the commands but refactors them to use strings (instead of C strings). Also it makes a few fixes on the start/stop/create_db script messages.

Test Plan: tested all options manually

Reviewers: vmerticariu

Differential Revision: http://codereview.rasdaman.org/D514

diff --git a/bin/create_db.sh.in b/bin/create_db.sh.in
--- a/bin/create_db.sh.in
+++ b/bin/create_db.sh.in
@@ -63,13 +63,25 @@ DEFINITION_FILE=@pkgdatadir@examples/rasdl/basictypes.dl
 
 # error termination routine
 error() {
-  echo
+	echo
 	echo "$PROG: $1" >&2
 	exit $RC_ERROR
 }
 
+log()
+{
+  echo "$PROG: $*"
+}
+
+logn()
+{
+  echo -n "$PROG: $*"
+}
+
+log "creating database, rasdaman v$VERSION on base DBMS $BASEDBMS"
+
 # --- checking preconditions
-echo "$PROG: Creating database, rasdaman v$VERSION on base DBMS $BASEDBMS"
+
 # - Can I find utilities?
 if [ "$BASEDBMS" == "$BASEDBMS_PGSQL" ]; then
     psql --help 2>&1 1>/dev/null || \
@@ -90,43 +102,47 @@ fi
 # --- action: create database directory & cluster if needed
 
 if [ "$BASEDBMS" == "$BASEDBMS_PGSQL" ]; then
-    echo -n "$PROG: PostgreSQL database generation... "
-
-    # - PostgreSQL part
-    createdb $DATABASE_NAME || error "createdb failed creating PostgreSQL database $DATABASE_NAME."
+    logn "PostgreSQL database generation... "
+    createdb $DATABASE_NAME > /dev/null || error "createdb failed creating PostgreSQL database $DATABASE_NAME."
     echo "ok."
 fi
-
-# - rasdaman part
-
-echo -n "$PROG: rasdaman dictionary initialization... "
 
 # - check if user has rights to create SQLite database
 if [ "$BASEDBMS" == "$BASEDBMS_SQLITE" ]; then
   datadir=$(dirname "@dbconn@")
   if [ ! -d "$datadir" ]
   then
-    echo
-    echo -n "$PROG: Filestorage directory '$datadir' not found, creating... "
+    logn "filestorage directory '$datadir' not found, creating... "
     mkdir -p "$datadir" || error "failed creating filestorage directory '$datadir'."
     echo "ok."
   fi
   if [ ! -w "$datadir" ]
   then
-    error "$PROG: User '$USER' has no write permissions in '$datadir', rasdaman database cannot be created."
+    error "Error: User '$USER' has no write permissions in '$datadir', rasdaman database cannot be created."
   fi
   if [ ! -x "$datadir" ]
   then
-    error "$PROG: User '$USER' has no execute permissions in '$datadir' (and/or parent directories), rasdaman database cannot be created."
+    error "Error: User '$USER' has no execute permissions in '$datadir' (and/or parent directories), rasdaman database cannot be created."
   fi
 fi
 
-@bindir@rasdl -c --connect @dbconn@ || error "rasdl failed creating RASBASE."
-@bindir@rasdl -r $DEFINITION_FILE -i --connect @dbconn@ || error "rasdl failed reading standard type definitions."
+# - rasdaman part
+
+log "rasdaman dictionary initialization... "
+
+logn "  creating RASBASE... "
+@bindir@rasdl -c --connect @dbconn@ > /dev/null || \
+  error "rasdl failed creating RASBASE."
+echo "ok."
+
+logn "  inserting standard types... "
+@bindir@rasdl -r $DEFINITION_FILE -i --connect @dbconn@ > /dev/null || \
+  error "rasdl failed reading standard type definitions."
+echo "ok."
 
 # --- action end 
 
-echo "$PROG: done."
+log "done."
 exit $RC_OK
 
 # --- end of script
diff --git a/bin/start_rasdaman.sh.in b/bin/start_rasdaman.sh.in
--- a/bin/start_rasdaman.sh.in
+++ b/bin/start_rasdaman.sh.in
@@ -79,6 +79,29 @@ logn()
   echo -n "$PROG: $*"
 }
 
+# give rasserver processes time to disappear (10 second timeout)
+wait_for_rasservers_to_shutdown()
+{
+count=0
+while [ $count -lt 100 ]; do
+    pgrep rasserver > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        break # no rasservers found, no need to wait more
+    fi
+    count=$(($count+1))
+    # otherwise, wait 0.1 seconds and try again
+    # if sleep 0.1 fails (0.1 not supported), try sleep 1
+    sleep 0.1 || sleep 1
+done
+if [ $count -eq 100 ]; then
+    echo
+    log "timeout of 10 seconds on waiting for rasserver processes to shutdown reached;"
+    log "please manually check and kill any still running rasserver processes:"
+    log " 1. list the running rasserver processes: pgrep rasserver"
+    log " 2. kill each process with: kill <pid> (or kill -9 <pid> if kill fails)"
+fi
+}
+
 # Read the property of a value by input key from input properties file
 get_property_value() {
     # $1 is path to input properties file (e.g: /opt/rasdaman/etc/petascope.properties).
@@ -116,9 +139,11 @@ rm -f nohup.out
 
 # start rasdaman server manager as demon; log will go into nohup.out
 # the manager is started in quiet mode
-nohup @bindir@rasmgr --port $RASMGR_PORT & 2>&1
+logn "  starting rasmgr... "
+nohup @bindir@rasmgr --port $RASMGR_PORT > nohup.out 2>&1 &
 rasmgr_pid=$!
 sleep 1
+echo "ok, pid $rasmgr_pid."
 
 # --- start servers: -------------------------------------------------
 
@@ -161,27 +186,37 @@ fi
 if [ "$SERVERS" ]; then
     for SRV in $SERVERS
     do
-        logn "starting server $SRV..."
+        logn "  starting server $SRV... "
         @bindir@rascontrol --port $RASMGR_PORT -e -q -x up srv $SRV || exit $!
-        echo "done."
+        echo "ok."
     done
 else
-    log "starting all rasdaman servers..."
+    logn "  starting all rasdaman servers... "
     @bindir@rascontrol --port $RASMGR_PORT -e -q -x up srv -all || exit $!
+    echo "ok."
 fi
 
 # do a rasql query test to check if rasdaman has started properly
+logn "running check query... "
 sleep 1
 @bindir@rasql -q 'select version()' --quiet -p $RASMGR_PORT > /dev/null 2>&1
 if [ $? -ne 0 ]; then
-    log "failed starting rasservers; please check the logs for more information."
-    logn "shutting down rasdaman... "
+    echo "failed; please check the logs for more information."
+
+    logn "  shutting down rasdaman... "
     # shut down any rasservers just in case
-    @bindir@rascontrol --port $RASMGR_PORT -e -q -x down srv -all -kill
-    sleep $WAIT_FOR_CHILDREN
+    @bindir@rascontrol --port $RASMGR_PORT -e -q -x down srv -all -kill > /dev/null
+    wait_for_rasservers_to_shutdown
     # kill rasmgr
-    @bindir@rascontrol --port $RASMGR_PORT -e -q -x down host -all -kill
+    @bindir@rascontrol --port $RASMGR_PORT -e -q -x down host -all -kill > /dev/null
+    pgrep rasserver > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        echo ok.
+    fi
+    log "done."
     exit $RC_ERROR
+else
+    echo "ok."
 fi
 
 #------start embedded petascope/secore if needed--------------------------
diff --git a/bin/stop_rasdaman.sh.in b/bin/stop_rasdaman.sh.in
--- a/bin/stop_rasdaman.sh.in
+++ b/bin/stop_rasdaman.sh.in
@@ -119,6 +119,28 @@ secore_properties_path="@sysconfdir@/secore.properties"
 stop_embedded "$secore_properties_path" "secore"
 stop_embedded "$petascope_properties_path" "petascope"
 
+# give rasserver processes time to disappear (10 second timeout)
+wait_for_rasservers_to_shutdown()
+{
+count=0
+while [ $count -lt 100 ]; do
+    pgrep rasserver > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        break # no rasservers found, no need to wait more
+    fi
+    count=$(($count+1))
+    # otherwise, wait 0.1 seconds and try again
+    # if sleep 0.1 fails (0.1 not supported), try sleep 1
+    sleep 0.1 || sleep 1
+done
+if [ $count -eq 100 ]; then
+    log "timeout of 10 seconds on waiting for rasserver processes to shutdown reached;"
+    log "please manually check and kill any still running rasserver processes:"
+    log " 1. list the running rasserver processes: pgrep rasserver"
+    log " 2. kill each process with: kill <pid> (or kill -9 <pid> if kill fails)"
+fi
+}
+
 # check if rasmgr is running first of all
 pgrep rasmgr > /dev/null 2>&1
 if [ $? -ne 0 ]; then
@@ -135,7 +157,7 @@ if [ -z "$RASLOGIN" ]; then
 fi
 
 # determine a list of all currently running servers
-ALLSERVERS=`@bindir@rascontrol --port $RASMGR_PORT -e -q -x list srv | awk '{ if (\$6 == "UP") print \$2;}'`
+ALLSERVERS=`@bindir@rascontrol --port $RASMGR_PORT -e -q -x list srv -all | awk '{ if (\$6 == "UP") print \$2;}'`
 
 # ...and shut down all of them, forcefully (!); any open transaction will be lost
 for SRV in $ALLSERVERS; do
@@ -144,25 +166,13 @@ for SRV in $ALLSERVERS; do
     echo "done."
 done
 
+wait_for_rasservers_to_shutdown
+
 # --- stop rasmgr -------------------------------------------------
 
-# give rasserver processes time to disappear (10 second timeout)
-count=0
-while [ $count -lt 100 ]; do
-    pgrep rasserver > /dev/null 2>&1
-    if [ $? -ne 0 ]; then
-        break # no rasservers found, no need to wait more
-    fi
-    count=$(($count+1))
-    # otherwise, wait 0.1 seconds and try again
-    # if sleep 0.1 fails (0.1 not supported), try sleep 1
-    sleep 0.1 || sleep 1
-done
-
 # finally shut down the server manager
-logn "terminating rasdaman server manager(s)..."
+logn ""
 @bindir@rascontrol --port $RASMGR_PORT -e -q -x down host -all
-echo "done."
 
 log "done."
 
