ticket:886 - improve transaction handling in blob file storage
Summary: Add transaction capabilities to the blob file storage that is synced with the SQLite RASBASE transaction. It uses the $RASDATA/TRANSACTIONS directory (next to the new TILES dir) for this purpose.

Test Plan:
Unit tests: cd relblobif/test && make check. I haven't seen any corruption yet by running systemtest/testcases_manual/test_crash_rasserver/test.sh, whereas it occurs rather often without this patch.
Still todo: extend test_crash_rasserver to test parallel querying. I'll do that while the review is going on.

Reviewers: gmerticariu, mdumitru, atoader

Reviewed By: gmerticariu, mdumitru, atoader

Subscribers: gmerticariu, vmerticariu

Differential Revision: http://codereview.rasdaman.org/D31

diff --git a/bin/create_db.sh.in b/bin/create_db.sh.in
--- a/bin/create_db.sh.in
+++ b/bin/create_db.sh.in
@@ -113,6 +113,11 @@ echo -n "$PROG: rasdaman dictionary initialization...\c"
 # - check if user has rights to create SQLite database
 if [ "$BASEDBMS" == "$BASEDBMS_SQLITE" ]; then
   datadir=$(dirname "@dbconn@")
+  if [ ! -d "$datadir" ]
+  then
+    echo "$MYNAME: Filestorage directory $datadir does not exist, rasdaman database cannot be created." >&2
+    exit $RC_ERROR
+  fi
   if [ ! -w "$datadir" ]
   then
     echo "$MYNAME: User $USER has no write permissions in $datadir, rasdaman database cannot be created." >&2
diff --git a/bin/update_db.sh.in b/bin/update_db.sh.in
--- a/bin/update_db.sh.in
+++ b/bin/update_db.sh.in
@@ -230,6 +230,16 @@ else
 
   log "rasdaman data directory: $RASDATA"
 
+  # determine file data dir
+  if [ -z "$RASDATA" ]; then
+    export RASDATA="@filedatadir@"
+    [ -n "$RASDATA" ] || error "please export RASDATA to point to the rasdaman data directory"
+  fi
+  [ -d "$RASDATA" ] || error "rasdaman data directory not found: $RASDATA"
+  [ -w "$RASDATA" -a -x "$RASDATA" ] || error "no write permissions to the rasdaman data directory: $RASDATA"
+
+  log "rasdaman data directory: $RASDATA"
+
   check_sqlite
 
   #
