ticket:1166 - make sure that globals.hh is used for default values, and add --port option sto start_rasdaman.sh and stop_rasdaman.sh

diff --git a/bin/create_db.sh.in b/bin/create_db.sh.in
--- a/bin/create_db.sh.in
+++ b/bin/create_db.sh.in
@@ -23,15 +23,9 @@
 #
 #
 # PURPOSE:
-#   This script creates a CREATE_DB.sql script for
-#   generating a rasdaman database with PostgreSQL.
-#   This script must be executed by the user which
-#   runs the PostgreSQL server.
-#
-#
-# COMMENTS:
-#   List environment dependencies, known bugs, specialities etc.
-#   -------------------------------------------------------------------
+#   This script initializes the RASBASE schema in postgres or sqlite
+#   (depending on how rasdaman was compiled), and creates the standard
+#   rasdaman types.
 #
 ########################################################################
 
@@ -39,7 +33,8 @@
 
 # script name
 PROG=$(basename $0)
-VERSION=9.8
+
+VERSION=@RMANVERSION@
 
 # script return codes
 RC_OK=0
@@ -49,8 +44,7 @@ BASEDBMS=@basedbms@
 BASEDBMS_SQLITE=sqlite
 BASEDBMS_PGSQL=pgsql
 
-# Unix user name under which rasdaman server is expected to run
-RASDAMAN_USER=rasdaman
+rasserver_bin="@bindir@rasserver"
 
 # default database name
 # (if you change this, then a _lot_ of tools and configs
@@ -60,25 +54,13 @@ DATABASE_NAME=RASBASE
 
 DBCONN="@dbconn@"
 
-# error termination routine
-error() {
-	echo
-	echo "$PROG: $1" >&2
-	exit $RC_ERROR
-}
-
-log()
-{
-  echo "$PROG: $*"
-}
-
-logn()
-{
-  echo -n "$PROG: $*"
-}
+log()  { echo "$PROG: $@"; }
+logn() { echo -n "$PROG: $@"; }
+error(){ echo "$PROG: $@" >&2; exit $RC_ERROR; }
+check(){ [ $? ] && echo "ok." || echo "failed."; }
 
 execute_query() {
-  @bindir@rasserver -q "$1" > /dev/null || \
+  $rasserver_bin -q "$1" > /dev/null || \
     error "failed executing query: $1"
 }
 
@@ -124,7 +106,7 @@ fi
 log "rasdaman dictionary initialization... "
 
 logn "  creating RASBASE... "
-@bindir@rasserver -c --connect "$DBCONN" > /dev/null || \
+$rasserver_bin -c --connect "$DBCONN" > /dev/null || \
   error "failed creating RASBASE."
 echo "ok."
 
diff --git a/bin/start_rasdaman.sh.in b/bin/start_rasdaman.sh.in
--- a/bin/start_rasdaman.sh.in
+++ b/bin/start_rasdaman.sh.in
@@ -53,6 +53,7 @@ PROG=$(basename $0)
 
 RC_OK=0       # everything went fine
 RC_ERROR=1    # something went wrong
+RC_HELP=2
 
 RASMGR_PORT=7001
 
@@ -135,13 +136,24 @@ check_port_available()
     fi
 }
 
+set_rasmgr_port()
+{
+    case "$1" in
+      ''|*[!0-9]*)  error "Invalid port specified: $1; expected a positive number <= 65535.";;
+      *)            RASMGR_PORT="$1";;
+    esac
+    [ $RASMGR_PORT -gt 0 -a $RASMGR_PORT -lt 65535 ] || \
+        error "Invalid port specified: $1; expected a positive number <= 65535."
+}
+
 #------ start embedded petascope/secore if needed --------------------------
 
 # Start embedded tomcat from values in properties file
 # $1: the path to properties file (e.g: /opt/rasdaman/etc/petascope.properties).
 # $2: the web application name (e.g: petascope, secore).
 # $3: the war file of application (e.g: rasdaman.war, def.war).
-start_embedded() {
+start_embedded()
+{
     local props_path="$1"
     local app_name="$2"
     local war_file_name="$3"
@@ -170,7 +182,34 @@ start_embedded() {
 
 # --- ACTION ------------------------------------------------------
 
-set_all_options() {
+usage()
+{
+    cat <<EOF
+Start the rasdaman server if not already running.
+
+Usage:
+  start_rasdaman.sh [OPTION]...
+
+Options:
+  --service <svc>       start a particular service <svc> only; allowed values 
+                        for <svc> are: core, petascope, secore. By default all
+                        services are started.
+
+  -p, --port <port>     specify the port on which rasmgr will listen. By default
+                        this is 7001, it is recommended to avoid changing this
+                        value unless really necessary.
+
+  <N1> <N2> ...         start only the specified rasservers, as named in 
+                        etc/rasmgr.conf. By default all configured rasservers 
+                        are started.
+
+  -h, --help            show this message and exit.
+EOF
+    exit $RC_HELP
+}
+
+set_all_options()
+{
     start_rasmgr_rasservers=$1
     start_embedded_petascope=$1
     start_embedded_secore=$1
@@ -193,13 +232,17 @@ for i in "$@"; do
               secore)    start_embedded_secore=true;;
               *)         error "Value for option $option must be core|petascope|secore. Given: $i";;
             esac
+        elif [ "$option" = "--port" -o "$option" = "-p" ]; then
+            set_rasmgr_port "$i"
         fi
         option=""
     else
         option=""
         case $i in
           --service)      option="$i";;
-          -*)            error "unknown option: $i";;
+          --port|-p)      option="$i";;
+          --help|-h)      usage;;
+          -*)             error "unknown option: $i";;
           *)              servers="$servers $i";;
         esac
     fi
diff --git a/bin/stop_rasdaman.sh.in b/bin/stop_rasdaman.sh.in
--- a/bin/stop_rasdaman.sh.in
+++ b/bin/stop_rasdaman.sh.in
@@ -50,6 +50,7 @@ PROG=$(basename $0)
 
 RC_OK=0       # everything went fine
 RC_ERROR=1    # something went wrong
+RC_HELP=2
 
 RASMGR_PORT=7001
 
@@ -143,7 +144,8 @@ check_port_available()
 # Stop embedded tomcat from values in properties file
 # $1: the path to properties file (e.g: /opt/rasdaman/etc/petascope.properties).
 # $2: the web application name (e.g: petascope, secore).
-stop_embedded() {
+stop_embedded()
+{
     local props_path="$1"
     local app_name="$2"
     local war_file_name="$3"
@@ -169,10 +171,42 @@ stop_embedded() {
     fi
 }
 
+set_rasmgr_port()
+{
+    case "$1" in
+      ''|*[!0-9]*)  error "Invalid port specified: $1; expected a positive number <= 65535.";;
+      *)            RASMGR_PORT="$1";;
+    esac
+    [ $RASMGR_PORT -gt 0 -a $RASMGR_PORT -lt 65535 ] || \
+        error "Invalid port specified: $1; expected a positive number <= 65535."
+}
 
 # --- ACTION ------------------------------------------------------
 
-set_all_options() {
+usage()
+{
+    cat <<EOF
+Stop the rasdaman server if it is currently running.
+
+Usage:
+  stop_rasdaman.sh [OPTION]...
+
+Options:
+  --service <svc>       stop a particular service <svc> only; allowed values 
+                        for <svc> are: core, petascope, secore. By default all
+                        services are stopped.
+
+  -p, --port <port>     specify the port on which rasmgr listens. If rasdaman
+                        was started with a port different from the standard 7001
+                        then the port must be specified with this option as well.
+
+  -h, --help            show this message and exit.
+EOF
+    exit $RC_HELP
+}
+
+set_all_options()
+{
     stop_all_services=$1
     stop_rasmgr_rasservers=$1
     stop_embedded_petascope=$1
@@ -194,12 +228,16 @@ for i in "$@"; do
               secore)    stop_embedded_secore=true;;
               *)         error "Value for option $option must be core|petascope|secore. Given: $i";;
             esac
+        elif [ "$option" = "--port" -o "$option" = "-p" ]; then
+            set_rasmgr_port "$i"
         fi
         option=""
     else
         option=""
         case $i in
-          --service) option="$i";;
+          --service)      option="$i";;
+          --port|-p)      option="$i";;
+          --help|-h)      usage;;
           *) error "unknown option: $i";;
         esac
     fi
