ticket:1542 - check if rasdaman is properly started and stop it if it is not.
Summary:
when rasservers fail to initialize properly, rasmgr will keep trying to restart them (every 3 seconds by default), unnecessarily producing many log files.
To fix this start_rasdaman.sh will try a simple select query after starting rasservers; if it fails to execute it means that no rasserver has probably started (select version() should always execute fine otherwise).
In this case it shuts down rasmgr and hence prevents it going into the above loop of constantly restarting the rasservers.

Test Plan: I've tested this manually by inserting a segfault into rasserver's initialization. It would be very hard to automate a test for this.

Reviewers: vmerticariu, bphamhuu

Reviewed By: vmerticariu, bphamhuu

Differential Revision: http://codereview.rasdaman.org/D385

diff --git a/bin/start_rasdaman.sh.in b/bin/start_rasdaman.sh.in
--- a/bin/start_rasdaman.sh.in
+++ b/bin/start_rasdaman.sh.in
@@ -64,7 +64,7 @@ RASMGR_PORT=7001
 DEFAULT_RASCONTROL_LOGIN=rasadmin:d293a15562d3e70b6fdc5ee452eaed40
 
 # sleep time to let rasmgr establish before spawning servers
-WAIT_FOR_CHILDREN=5
+WAIT_FOR_CHILDREN=1
 
 # error messages:
 ERROR_PARAM="ERS001 Error: illegal parameter: $1"
@@ -116,14 +116,23 @@ rm -f nohup.out
 # start rasdaman server manager as demon; log will go into nohup.out
 # the manager is started in quiet mode
 nohup @bindir@rasmgr --port $RASMGR_PORT & 2>&1
+rasmgr_pid=$!
 
 # --- start servers: -------------------------------------------------
 
 # allow process to establish
 sleep $WAIT_FOR_CHILDREN
 
+# check if rasmgr's pid is actually running; if not, exit with an error.
+# we do it this way, because the exit code cannot be captured with nohup
+ps -p $rasmgr_pid > /dev/null
+if [ $? -ne 0 ]; then
+    echo "$MYNAME: rasmgr failed starting; please check the logs for more information."
+    exit $RC_ERROR
+fi
+
 # these servers will be started:
-if [ $1 ]
+if [ -n "$1" ]
 then
     # parameters provided, take them as server names
     # B: check if parameter's name does not start with -- then it is the server name
@@ -131,14 +140,13 @@ then
     for var in "$@"
     do
         if [[ "$var" != *"--"* ]]; then
-        # this is server name so add to SERVERS
-        SERVERS+="$var"' ';
-            #echo $var
+            # this is server name so add to SERVERS
+            SERVERS+="$var"' '
         fi
     done
 
 else
-    if [ "$RASSERVERS" ]; then
+    if [ -n "$RASSERVERS" ]; then
         SERVERS=$RASSERVERS
     else
         SERVERS=""
@@ -162,6 +170,18 @@ else
     @bindir@rascontrol --port $RASMGR_PORT -e -q -x up srv -all || exit $!
 fi
 
+# do a rasql query test to check if rasdaman has started properly
+@bindir@rasql -q 'select version()' --quiet -p $RASMGR_PORT > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+    echo "$MYNAME: failed starting rasservers; please check the logs for more information."
+    echo -n "$MYNAME: shutting down rasdaman... "
+    # shut down any rasservers just in case
+    @bindir@rascontrol --port $RASMGR_PORT -e -q -x down srv -all -kill
+    sleep $WAIT_FOR_CHILDREN
+    # kill rasmgr
+    @bindir@rascontrol --port $RASMGR_PORT -e -q -x down host -all -kill
+    exit $RC_ERROR
+fi
 
 #---------------------------------------------------
 
diff --git a/bin/stop_rasdaman.sh.in b/bin/stop_rasdaman.sh.in
--- a/bin/stop_rasdaman.sh.in
+++ b/bin/stop_rasdaman.sh.in
@@ -48,12 +48,13 @@
 
 MYNAME=`basename $0`
 
+# RETURN CODES
+RC_OK=0        # everything went fine
+RC_ERROR=1    # something went wrong
+
 RASMGR_PORT=7001
 # rasadmin/rasadmin
 DEFAULT_RASCONTROL_LOGIN=rasadmin:d293a15562d3e70b6fdc5ee452eaed40
-
-# sleep time to let rasmgr shutdown servers first
-WAIT_FOR_CHILDREN=5
 
 # base DBMS used by petascope
 PETASCOPEDB=@petascopedb@
@@ -68,6 +69,12 @@ JETTY_JAR=jetty.jar
 
 # --- ACTION --------------------------------------------------------
 
+# check if rasmgr is running first of all
+pgrep rasmgr > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+    echo $MYNAME: rasdaman is already down, nothing to do.
+    exit $RC_OK
+fi
 
 echo $MYNAME: terminating all rasdaman servers
 
@@ -90,8 +97,18 @@ done
 
 # --- stop rasmgr: -------------------------------------------------
 
-# give rasserver processes time to disappear
-sleep $WAIT_FOR_CHILDREN
+# give rasserver processes time to disappear (10 second timeout)
+count=0
+while [ $count -lt 100 ]; do
+    pgrep rasserver > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        break # no rasservers found, no need to wait more
+    fi
+    count=$(($count+1))
+    # otherwise, wait 0.1 seconds and try again
+    # if sleep 0.1 fails (0.1 not supported), try sleep 1
+    sleep 0.1 || sleep 1
+done
 
 # finally shut down the server manager
 echo -n "terminating rasdaman server manager(s)..."
