ticket:1599 - Update SECORE to use Spring Boot framework
Summary:
Changed SECORE servlet to use Spring Controller (the main change of source code) and arranged to one secore source folder.
Also, added embedded petascope, secore to be able to start/stop with start_rasdaman.sh/stop_rasdaman.sh.

Test Plan: Run test system for secore, test all wcst_import.

Reviewers: dmisev

Differential Revision: http://codereview.rasdaman.org/D474

diff --git a/bin/start_rasdaman.sh.in b/bin/start_rasdaman.sh.in
--- a/bin/start_rasdaman.sh.in
+++ b/bin/start_rasdaman.sh.in
@@ -15,7 +15,7 @@
 # You should have received a copy of the GNU General Public License
 # along with rasdaman community.  If not, see <http://www.gnu.org/licenses/>.
 #
-# Copyright 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015 Peter Baumann /
+# Copyright 2003 - 2017 Peter Baumann /
 # rasdaman GmbH.
 #
 # For more information please see <http://www.rasdaman.org>
@@ -51,7 +51,7 @@
 #
 
 # get script name
-MYNAME=`basename $0`
+PROG=`basename $0`
 
 # RETURN CODES
 RC_OK=0        # everything went fine
@@ -68,25 +68,29 @@ ERROR_PARAM="ERS001 Error: illegal parameter: $1"
 
 # base DBMS used by petascope
 PETASCOPEDB=@petascopedb@
-PETASCOPEDB_PGSQL=postgresql
-PETASCOPEDB_HSQLDB=hsqldb
-PETASCOPEDB_SQLITE=sqlite
 
-# check if "java_server" is embedded and start_embedded_petascope is true then user can start embedded jetty petascope
-JAVA_SERVER_EMBEDDED=embedded
+log()
+{
+  echo "$PROG: $*"
+}
 
-START_EMBEDDED_PETASCOPE="start_embedded_petascope"
-STOP_EMBEDDED_PETASCOPE="stop_embedded_petascope"
+logn()
+{
+  echo -n "$PROG: $*"
+}
 
-# JETTY JAR
-JETTY_JAR=jetty.jar
+# Read the property of a value by input key from input properties file
+get_property_value() {
+    # $1 is path to input properties file (e.g: /opt/rasdaman/etc/petascope.properties).
+    # $2 is the key of a property in this file which needs to get the value of this key.
+    local -r properties_file="$1"
+    local -r key="$2"
 
+    # only grep key=value line not commented line (e.g: #key=value)
+    grep "^$key=" "$properties_file" | sed -e 's/.*=//' -e 's/^[ \t]*//'
+} 
 
-# --- END CONSTANTS -------------------------------------------------
-
-# --- ACTION --------------------------------------------------------
-
-echo $MYNAME: starting rasdaman server complex...
+log "starting rasdaman server complex..."
 
 # --- start rasmgr: -------------------------------------------------
 
@@ -96,14 +100,14 @@ cd @logdir@
 # check if we can actually write anything here
 if [ ! -w . ]
 then
-    echo "$MYNAME: User $USER has no write permissions in @logdir@, rasdaman cannot be started." >&2
+    log "User $USER has no write permissions in @logdir@, rasdaman cannot be started." >&2
     exit $RC_ERROR
 fi
 
 # check if rasmgr exists
 if [ ! -f @bindir@rasmgr ];
 then
-    echo "$MYNAME: rasmgr does not exist in "@bindir@", rasdaman cannot be started."
+    log "rasmgr does not exist in "@bindir@", rasdaman cannot be started."
     exit $RC_ERROR
 fi
 
@@ -121,7 +125,7 @@ rasmgr_pid=$!
 # we do it this way, because the exit code cannot be captured with nohup
 ps -p $rasmgr_pid > /dev/null
 if [ $? -ne 0 ]; then
-    echo "$MYNAME: rasmgr failed starting; please check the logs for more information."
+    log "rasmgr failed starting; please check the logs for more information."
     exit $RC_ERROR
 fi
 
@@ -156,11 +160,11 @@ fi
 if [ "$SERVERS" ]; then
     for SRV in $SERVERS
     do
-        echo -n $MYNAME: starting server $SRV...
+        logn "starting server $SRV..."
         @bindir@rascontrol --port $RASMGR_PORT -e -q -x up srv $SRV || exit $!
     done
 else
-    echo $MYNAME: starting all rasdaman servers...
+    log "starting all rasdaman servers..."
     @bindir@rascontrol --port $RASMGR_PORT -e -q -x up srv -all || exit $!
 fi
 
@@ -168,8 +172,8 @@ fi
 sleep 0.1 || sleep 1
 @bindir@rasql -q 'select version()' --quiet -p $RASMGR_PORT > /dev/null 2>&1
 if [ $? -ne 0 ]; then
-    echo "$MYNAME: failed starting rasservers; please check the logs for more information."
-    echo -n "$MYNAME: shutting down rasdaman... "
+    log "failed starting rasservers; please check the logs for more information."
+    logn "shutting down rasdaman... "
     # shut down any rasservers just in case
     @bindir@rascontrol --port $RASMGR_PORT -e -q -x down srv -all -kill
     sleep $WAIT_FOR_CHILDREN
@@ -178,110 +182,52 @@ if [ $? -ne 0 ]; then
     exit $RC_ERROR
 fi
 
-#---------------------------------------------------
+#------start embedded petascope/secore if needed--------------------------
+log_path="@logdir@"
+# war files also copied to this share folder: /opt/rasdaman/share/rasdaman/war/
+war_path="@pkgdatadir@/war"
+petascope_properties_path="@sysconfdir@/petascope.properties"
+secore_properties_path="@sysconfdir@/secore.properties"
 
-#echo '----------------End Checking start Rasdaman Servers----------------'
+start_embedded() {
+    # Start embedded tomcat from values in properties file
+    # $1: the path to properties file (e.g: /opt/rasdaman/etc/petascope.properties).
+    # $2: the web application name (e.g: petascope, secore).
+    # $3: the war file of application (e.g: rasdaman.war, def.war).
+    local -r properties_file_path="$1"
+    local -r application_name="$2"
+    local -r war_file_name="$3"  
 
-# B: Embedded - Petascope
-configPath=@sysconfdir@; # /home/rasdaman/install/etc ($RMANHOME)
-installPath=$(echo ${configPath:0:-3}) # Get substring before '/etc' in file path (default is /home/rasdaman/install)
-petascopePath=$installPath'/share/rasdaman/war/' # Embedded Jetty and petascope directory: /home/rasdaman/install/share/rasdaman/war/
-petascopePropertiesFile=$installPath'etc/petascope.properties'
-
-# check if --disable-jave is off
-if [ -f "$petascopePropertiesFile" ]; then
-
-    # check if java-server is embedded/external
-    javaServer=$(cat "$petascopePropertiesFile" | grep 'java_server'  | awk -F "=" '{print $2}');
-    javaServer=$(echo $javaServer | sed -e 's/^[ \t]*//')
-
-    # check if java-server is embedded
-    if [ "$javaServer" == "$JAVA_SERVER_EMBEDDED" ]; then
-
-        # 1. Check if user wants to start or stop petascope "manually" when execute start_rasdaman.sh with parameter --start-embedded-petascope or --stop--embedded-petascope
-
-        # normally if user does not add on of these arguments, need to check the configuration in petascope.properties
-        startPetascope=$(cat "$petascopePropertiesFile" | grep "$START_EMBEDDED_PETASCOPE"  | awk -F "=" '{print $2}');
-        startPetascope=$(echo $startPetascope | sed -e 's/^[ \t]*//')
-
-        # 2. User wants to start or stop petascope "manually" then iterate the inputs to get this kind of argument (ignores server names)
-        for var in "$@"
-        do
-            if [ "$var" == "--start-embedded-petascope" ]; then
-                startPetascope=true;
-            elif [ "$var" == "--stop-embedded-petascope" ]; then
-                startPetascope=false;
+    if [ -f "$properties_file_path" ]; then
+        # check if java-server is embedded/external
+        java_server=$(get_property_value "$properties_file_path" "java_server")
+        # check if java-server is embedded
+        if [ "$java_server" == "embedded" ]; then
+            # Get the embedded port for server
+            server_port=$(get_property_value "$properties_file_path" "server.port")
+            # Check if port is available
+            fuser -s -n tcp "$server_port"   
+             # Return 1 means port is available  
+            if [[ ! $? -eq 0 ]]; then
+                nohup java -jar "$war_path/""$war_file_name" & 2>&1
+                log "embedded $application_name is starting on port '$server_port'..."
+                log "check $log_path/$application_name.log for detail."
+            else
+                log "port '$server_port' is occupied, cannot start embedded $application_name."
+                exit $RC_ERROR
             fi
-        done
-
-        # 3. Check value of startPetascope: if it is true then start embedded petascope
-        if [ "$startPetascope" = true ]; then
-
-            # get the pid of last embedded Jetty with petascope (only 1 process is allowed to run in background)
-            # the [] is trick to avoid grep's pid is chosen instead of running Jetty.
-
-            pid=$(ps -ef | grep '[r]asdaman/war/'$JETTY_JAR | awk '{print $2; exit}')
-
-            # check pid of Jetty, if it is empty then could start Jetty
-            if [[ -z "$pid" ]]; then
-                echo $MYNAME: 'embedded petascope is starting.....'
-
-                # First, check if port of Jetty is not used by other applications.
-                portJetty=$(cat "$petascopePropertiesFile" | grep 'jetty_port'  | awk -F "=" '{print $2}')
-                portJetty=$(echo $portJetty | sed -e 's/^[ \t]*//')
-
-                # check if port is open or not, 2>/dev/null to clean the warning: 'you must be root when using netstat'
-                isPortUsed=$(netstat -anpp 2>/dev/null | grep "$portJetty" | awk '{print $6}')
-
-                # If port is used (LISTEN) then could not use this port
-                if [[  "$isPortUsed" =~ 'LISTEN' ]]; then
-                    echo $MYNAME: 'starting embedded petascope failed, conflicts with port number: "'$portJetty'"';
-                    echo 'Please change port (jetty_port=) in file: '"$petascopePropertiesFile"
-                else
-                    echo $MYNAME: 'starting embedded petascope with port number: "'$portJetty'"';
-
-                    # Running Jetty-petascope as background processs and write log file to jetty."portJetty".log in install folder (i.e. $RMANHOME/log)
-                    java -cp "$petascopePath$JETTY_JAR"':'$petascopePath start_petascope "$installPath" > "$installPath"'/log/jetty.'"$portJetty"'.log' 2>&1 &
-
-                    # Check if Jetty has started successful
-                    # get the pid of last embedded Jetty with petascope (only 1 process is allowed to run in background)
-                    # the [] is trick to avoid grep's pid is chosen instead of running Jetty.
-                    pid=$(ps -ef | grep '[r]asdaman/war/'$JETTY_JAR | awk '{print $2; exit}')
-
-                    # check if petascope is running
-                    if [[ ! -z "$pid" ]]; then
-                        echo $MYNAME: 'pid of last embedded petascope: "'$pid'". Done.' # success
-                    else
-                        echo $MYNAME: 'start embedded petascope unsuccessful. Is Jetty running? Hint: ps -ef | grep "jetty". ' # fail
-                    fi # end checking if petascope is running
-                fi # end checking port has opened
-            else # petascope is running
-                echo $MYNAME: 'pid of last embedded petascope = "'$pid'"'
-            fi # end checking if petascope is running
-        else # check startPetascope is false
-            echo $MYNAME: "petascope will not be started."
-        fi # end checking startPetascope is true
-    fi; # end checking java-server is embedded
-fi; # end checking --disable-java is off
-
-#---------------------------------------------------
-
-# if HSQLDB is used for petascope, start HSQLDB server here
-if [ "$PETASCOPEDB" == "$PETASCOPEDB_HSQLDB" ]; then
-    metadata_url=$(grep metadata_url @sysconfdir@/petascope.properties | awk -F "=" '{print $2}' | tr -d '\n')
-    db_name=$(basename "$metadata_url")
-    db_file=$(echo "$metadata_url" | awk -F ":" '{ print $NF; }')
-    echo -n $MYNAME: starting petascope...
-    nohup java -cp @libdir@/hsqldb.jar org.hsqldb.server.Server --database.0 file:$db_file --dbname.0 $db_name > @logdir@/hsqldb.log 2>&1 &
-    if [ $? -eq 0 ]; then
-        echo done.
+        fi
     else
-        echo "failed, see @logdir@/hsqldb.log for more details."
+        log "could not find properties file '$properties_file_path' to start embedded $application_name."
+        exit $RC_ERROR
     fi
-fi
+}
 
+# Check if it should start embedded tomcat, secore
+start_embedded "$secore_properties_path" "secore" "def.war"
+start_embedded "$petascope_properties_path" "petascope" "rasdaman.war"
 
-echo $MYNAME: done.
+echo "done."
 exit $RC_OK
 
 # --- END ACTION ----------------------------------------------------
diff --git a/bin/stop_rasdaman.sh.in b/bin/stop_rasdaman.sh.in
--- a/bin/stop_rasdaman.sh.in
+++ b/bin/stop_rasdaman.sh.in
@@ -46,7 +46,7 @@
 
 # --- CONSTANTS -----------------------------------------------------
 
-MYNAME=`basename $0`
+PROG=`basename $0`
 
 # RETURN CODES
 RC_OK=0        # everything went fine
@@ -58,27 +58,77 @@ DEFAULT_RASCONTROL_LOGIN=rasadmin:d293a15562d3e70b6fdc5ee452eaed40
 
 # base DBMS used by petascope
 PETASCOPEDB=@petascopedb@
-PETASCOPEDB_PGSQL=postgresql
-PETASCOPEDB_HSQLDB=hsqldb
-PETASCOPEDB_SQLITE=sqlite
 
-# JETTY JAR
-JETTY_JAR=jetty.jar
+log()
+{
+  echo "$PROG: $*"
+}
 
-# --- END CONSTANTS -------------------------------------------------
+logn()
+{
+  echo -n "$PROG: $*"
+}
 
-# --- ACTION --------------------------------------------------------
+# Read the property of a value by input key from input properties file
+get_property_value() {
+    # $1 is path to input properties file (e.g: /opt/rasdaman/etc/petascope.properties).
+    # $2 is the key of a property in this file which needs to get the value of this key.
+    local -r properties_file="$1"
+    local -r key="$2"
+
+    # only grep key=value line not commented line (e.g: #key=value)
+    grep "^$key=" "$properties_file" | sed -e 's/.*=//' -e 's/^[ \t]*//'
+}
+
+# --- kill embedded petascope, secore if they are running ---------
+
+stop_embedded() {
+    # Stop embedded tomcat from values in properties file
+    # $1: the path to properties file (e.g: /opt/rasdaman/etc/petascope.properties).
+    # $2: the web application name (e.g: petascope, secore).
+    local -r properties_file_path="$1"
+    local -r application_name="$2"
+
+    if [ -f "$properties_file_path" ]; then
+        # check if java-server is embedded/external
+        java_server=$(get_property_value "$properties_file_path" "java_server")
+        # check if java-server is embedded
+        if [ "$java_server" == "embedded" ]; then
+            # Check if the port for this application is running and kill this process
+            # Get the embedded port for server
+            server_port=$(get_property_value "$properties_file_path" "server.port")
+            # Check if port is available
+            fuser -s -n tcp "$server_port" 
+            # Return 0 means port is occupied and embedded server is running.
+            if [[ $? -eq 0 ]]; then
+                # kill process on this port
+                kill -9 $(lsof -t -i:"$server_port" -sTCP:LISTEN)
+                log "embedded $application_name is terminated on port '$server_port'."
+            fi
+        fi
+    else
+        log "could not find properties file '$properties_file_path' to stop embedded $application_name."
+        exit $RC_ERROR
+    fi
+}
+
+petascope_properties_path="@sysconfdir@/petascope.properties"
+secore_properties_path="@sysconfdir@/secore.properties"
+
+# Check if it should stop embedded tomcat, secore
+stop_embedded "$secore_properties_path" "secore"
+stop_embedded "$petascope_properties_path" "petascope"
 
 # check if rasmgr is running first of all
 pgrep rasmgr > /dev/null 2>&1
 if [ $? -ne 0 ]; then
-    echo $MYNAME: rasdaman is already down, nothing to do.
+    log "rasdaman is already down, nothing to do."
     exit $RC_OK
 fi
 
-echo $MYNAME: terminating all rasdaman servers
+log "terminating all rasdaman servers"
 
-# --- stop rasdaman servers: ---------------------------------------
+# --- stop rasdaman servers ---------------------------------------
 
 if [ -z "$RASLOGIN" ]; then
     export RASLOGIN=$DEFAULT_RASCONTROL_LOGIN
@@ -88,14 +138,13 @@ fi
 ALLSERVERS=`@bindir@rascontrol --port $RASMGR_PORT -e -q -x list srv | awk '{ if (\$6 == "UP") print \$2;}'`
 
 # ...and shut down all of them, forcefully (!); any open transaction will be lost
-for SRV in $ALLSERVERS
-do
-    echo -n $MYNAME: terminating server $SRV...
+for SRV in $ALLSERVERS; do
+    logn "terminating server $SRV..."
     @bindir@rascontrol --port $RASMGR_PORT -e -q -x down srv $SRV -kill
     echo "done."
 done
 
-# --- stop rasmgr: -------------------------------------------------
+# --- stop rasmgr -------------------------------------------------
 
 # give rasserver processes time to disappear (10 second timeout)
 count=0
@@ -111,45 +160,10 @@ while [ $count -lt 100 ]; do
 done
 
 # finally shut down the server manager
-echo -n "terminating rasdaman server manager(s)..."
+logn "terminating rasdaman server manager(s)..."
 @bindir@rascontrol --port $RASMGR_PORT -e -q -x down host -all
+log "done."
+
 echo "done."
-
-
-
-# if HSQLDB is used for petascope, stop HSQLDB server here
-if [ "$PETASCOPEDB" == "$PETASCOPEDB_HSQLDB" ]; then
-    metadata_url=$(grep metadata_url @sysconfdir@/petascope.properties | awk -F "=" '{print $2}' | tr -d '\n')
-    db_name=$(basename "$metadata_url")
-    db_file=$(echo "$metadata_url" | awk -F ":" '{ print $NF; }')
-    echo -n "$MYNAME: terminating petascope database..."
-    kill $(pgrep -f org.hsqldb.server.Server)
-    echo "done."
-fi
-
-# --- B: Terminate Embedded Petascope if it is running ----------------------------------------------------
-
-# get the pid of lasted embedded Jetty with Petascope (only 1 process is allowed to run in background)
-# the [] is trick to avoid grep's pid is chosen instead of running Jetty.
-pid=$(ps -ef | grep '[r]asdaman/war/jetty.jar' | awk '{print $2; exit}')
-
-if [[ ! -z "$pid" ]]; then # pid is not empty then need to terminate running embedded Petascope
-    kill -9 $pid;
-    # get the pid of lasted embedded Jetty with Petascope (only 1 process is allowed to run in background)
-    # the [] is trick to avoid grep's pid is chosen instead of running Jetty.
-    repid=$(ps -ef | grep '[r]asdaman/war/'$JETTY_JAR | awk '{print $2; exit}')
-
-    if [[ ! -z "$redpid" ]]; then # redpid is not empty then need to have an error
-        echo $MYNAME: 'terminate embedded petascope unsuccessfully. Please kill PID: "'$repid'" manually..Done.'
-    else
-        echo $MYNAME: 'terminating embedded petascope successfully...Done.'
-    fi
-fi
-
-
-# --- END ACTION ----------------------------------------------------
-
-
-echo $MYNAME: done.
 exit $RC_OK
 
