ticket:958 - update_db.sh script does not work for sqlite

diff --git a/bin/update_db.sh.in b/bin/update_db.sh.in
--- a/bin/update_db.sh.in
+++ b/bin/update_db.sh.in
@@ -42,8 +42,8 @@
 
 PROG=`basename $0`
 
-CODE_OK=0
-CODE_FAIL=255
+RC_OK=0
+RC_ERROR=255
 
 # updateN.sql scripts
 SCRIPT_DIR=@pkgdatadir@/db_updates
@@ -51,6 +51,12 @@ SCRIPT_DIR=@pkgdatadir@/db_updates
 # table storing the current database update number
 RAS_DBUPDATE=ras_dbupdates
 DB_TYPE=rc
+
+BASEDBMS=@basedbms@
+BASEDBMS_SQLITE=sqlite
+BASEDBMS_PGSQL=pgsql
+
+export DBCONN=@dbconn@
 
 # ------------------------------------------------------------------------------
 # functions
@@ -68,13 +74,13 @@ logn() {
 error() {
   echo "$PROG: $*" >&2
   echo "$PROG: exiting." >&2
-  exit $CODE_FAIL
+  exit $RC_ERROR
 }
 feedback() {
   if [ $? -ne 0 ]; then
     echo failed.
     echo "$PROG: exiting." >&2
-    exit $CODE_FAIL
+    exit $RC_ERROR
   else
     echo ok.
   fi
@@ -83,117 +89,205 @@ feedback() {
 #
 # checks
 #
-check_postgres() {
-  which psql > /dev/null || error "PostgreSQL missing, please add psql to the PATH."
-  pgrep postgres > /dev/null
+
+if [ ! -d "$SCRIPT_DIR" ]; then
+  error "SQL update script directory not found: $SCRIPT_DIR"
+fi
+
+if [ "$BASEDBMS" == "$BASEDBMS_PGSQL" ]; then
+
+  check_postgres() {
+    which psql > /dev/null || error "PostgreSQL missing, please add psql to the PATH."
+    pgrep postgres > /dev/null
+    if [ $? -ne 0 ]; then
+      pgrep postmaster > /dev/null || error "The PostgreSQL service is not started."
+    fi
+  }
+
+  # ------------------------------------------------------------------------------
+  # work
+  # ------------------------------------------------------------------------------
+
+  #
+  # postgres connection details (defaults used)
+  #
+  RAS_DB=${DBCONN-RASBASE}
+  RAS_PORT=${PGPORT-5432}
+
+
+  #
+  # commands
+  #
+  PSQL="psql -d $RAS_DB -p $RAS_PORT"
+  CREATEDB="createdb -p $RAS_PORT"
+
+  # print some info
+  log "postgres settings"
+  log "  port: $RAS_PORT"
+  log "  db: $RAS_DB"
+
+  check_postgres
+
+  #
+  # check if db is present
+  #
+  psql -p $RAS_PORT --list 2>&1 | egrep "\b$RAS_DB\b" > /dev/null
   if [ $? -ne 0 ]; then
-    pgrep postmaster > /dev/null || error "The PostgreSQL service is not started."
+    error "no $RAS_DB database found, please run create_db.sh first"
   fi
-}
-check_paths() {
-  if [ ! -d "$SCRIPT_DIR" ]; then
-    error "SQL update script directory not found: $SCRIPT_DIR"
-  fi
-}
-
-# ------------------------------------------------------------------------------
-# work
-# ------------------------------------------------------------------------------
-
-check_paths
-
-#
-# postgres connection details (defaults used)
-#
-RAS_DB=RASBASE
-RAS_PORT=${PGPORT-5432}
 
 
-#
-# commands
-#
-PSQL="psql -d $RAS_DB -p $RAS_PORT"
-CREATEDB="createdb -p $RAS_PORT"
-
-# print some info
-log "postgres settings"
-log "  port: $RAS_PORT"
-log "  db: $RAS_DB"
-
-check_postgres
-
-#
-# check if db is present
-#
-psql -p $RAS_PORT --list 2>&1 | egrep "\b$RAS_DB\b" > /dev/null
-if [ $? -ne 0 ]; then
-  error "no $RAS_DB database found, please run create_db.sh first"
-fi
-
-
-#
-# determine the update number
-#
-$PSQL -c "select * from $RAS_DBUPDATE" > /dev/null 2>&1
-if [ $? -ne 0 ]; then
-  # create from scratch
-	counter=0
-else
-  # check if there is an entry at all
-  count=`$PSQL -c "select count(UpdateNumber) from RAS_DBUPDATES where UpdateType='$DB_TYPE'" | head -n 3 | tail -n 1 | awk '{print $1}'`
-  if [ $count -gt 0 ]; then
-    # get the last update number
-    counter=`$PSQL -c "select UpdateNumber from $RAS_DBUPDATE where UpdateType='$DB_TYPE'" | head -n 3 | tail -n 1 | awk '{print $1}'`
-  else
+  #
+  # determine the update number
+  #
+  $PSQL -c "select * from $RAS_DBUPDATE" > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    # create from scratch
     counter=0
-    $PSQL -c "insert into $RAS_DBUPDATE values('$DB_TYPE', $counter)" > /dev/null 2>&1
-  fi
-fi
-
-#
-# some updates are written in PL/pgSQL, so install the extension in postgres
-#
-createlang plpgsql $RAS_DB > /dev/null 2>&1
-rc=$?
-if [ $rc -ne 0 -a $rc -ne 2 ]; then
-  error "failed creating PL/pgSQL extension in PostgreSQL, please install it first on your system."
-fi
-
-#
-# insert the database updates
-#
-echo
-log "executing updates:"
-updated=0
-while [ -f "$SCRIPT_DIR/update$counter.sql" ]; do
-  logn "  update $counter... "
-        # Note for future .sql files: do not add manual BEGIN/COMMIT transactions, they are handled by psql
-	$PSQL --set ON_ERROR_STOP=on --single-transaction -f "$SCRIPT_DIR/update$counter.sql" > /dev/null 2>&1
-	# Check if the update was successful
-	ret=$?
-	if [ "$ret" -ne 0 ]; then
-      echo "FAILED (return value $ret)."
-      break # So that ps_dbupdates is updated to its partial update anyway.
+  else
+    # check if there is an entry at all
+    count=`$PSQL -c "select count(UpdateNumber) from RAS_DBUPDATES where UpdateType='$DB_TYPE'" | head -n 3 | tail -n 1 | awk '{print $1}'`
+    if [ $count -gt 0 ]; then
+      # get the last update number
+      counter=`$PSQL -c "select UpdateNumber from $RAS_DBUPDATE where UpdateType='$DB_TYPE'" | head -n 3 | tail -n 1 | awk '{print $1}'`
     else
-      echo ok.
-	fi
-	counter=$(($counter+1))
-	updated=1
-done
+      counter=0
+      $PSQL -c "insert into $RAS_DBUPDATE values('$DB_TYPE', $counter)" > /dev/null 2>&1
+    fi
+  fi
 
-#
-# save the last update number
-#
-if [ $updated -eq 1 ]; then
-  $PSQL -c "update $RAS_DBUPDATE set UpdateNumber=$counter where UpdateType='$DB_TYPE'" > /dev/null 2>&1
-  log "updated database to update $((counter-1))"
+  #
+  # some updates are written in PL/pgSQL, so install the extension in postgres
+  #
+  createlang plpgsql $RAS_DB > /dev/null 2>&1
+  rc=$?
+  if [ $rc -ne 0 -a $rc -ne 2 ]; then
+    error "failed creating PL/pgSQL extension in PostgreSQL, please install it first on your system."
+  fi
+
+  #
+  # insert the database updates
+  #
+  echo
+  log "executing updates:"
+  updated=0
+  while [ -f "$SCRIPT_DIR/update$counter.sql" ]; do
+    logn "  update $counter... "
+          # Note for future .sql files: do not add manual BEGIN/COMMIT transactions, they are handled by psql
+    $PSQL --set ON_ERROR_STOP=on --single-transaction -f "$SCRIPT_DIR/update$counter.sql" > last.log 2>&1
+    # Check if the update was successful
+    ret=$?
+    if [ "$ret" -ne 0 ]; then
+        echo "FAILED (return value $ret)."
+        echo "Error: "$(cat last.log)
+        break # So that ps_dbupdates is updated to its partial update anyway.
+      else
+        echo ok.
+    fi
+    counter=$(($counter+1))
+    updated=1
+  done
+
+  #
+  # save the last update number
+  #
+  if [ $updated -eq 1 ]; then
+    $PSQL -c "update $RAS_DBUPDATE set UpdateNumber=$counter where UpdateType='$DB_TYPE'" > /dev/null 2>&1
+    log "updated database to update $((counter-1))"
+  else
+    log "database already up-to-date, nothing to update."
+  fi
+
 else
-  log "database already up-to-date, nothing to update."
+
+  check_sqlite() {
+    which sqlite3 > /dev/null || error "sqlite3 missing, please install."
+  }
+
+  # ------------------------------------------------------------------------------
+  # work
+  # ------------------------------------------------------------------------------
+
+  #
+  # commands
+  #
+  SQLITE="sqlite3 $DBCONN"
+
+  # print some info
+  log "sqlite database to update: $DBCONN"
+
+  check_sqlite
+
+  #
+  # check if db is present
+  #
+  if [ ! -f "$DBCONN" ]; then
+    error "no $DBCONN database found, please run create_db.sh first"
+  fi
+
+
+  #
+  # determine the update number
+  #
+  $SQLITE "select * from $RAS_DBUPDATE" > last.log 2>&1
+  if [ $? -ne 0 ]; then
+    # create from scratch
+    counter=0
+  else
+    # check if there is an entry at all
+    count=$($SQLITE "select count(UpdateNumber) from RAS_DBUPDATES where UpdateType='$DB_TYPE'" | head -n 1)
+    if [ $count -gt 0 ]; then
+      # get the last update number
+      counter=$($SQLITE "select UpdateNumber from $RAS_DBUPDATE where UpdateType='$DB_TYPE'" | head -n 1)
+    else
+      counter=0
+      $SQLITE "insert into $RAS_DBUPDATE values('$DB_TYPE', $counter)" > last.log 2>&1
+    fi
+  fi
+
+  #
+  # insert the database updates
+  #
+  echo
+  log "executing updates:"
+  updated=0
+  while [ -f "$SCRIPT_DIR/update${counter}-sqlite.sql" -o -f "$SCRIPT_DIR/update${counter}-sqlite.sh" ]; do
+    logn "  update $counter... "
+    if [ -f "$SCRIPT_DIR/update${counter}-sqlite.sql" ]; then
+      $SQLITE < "$SCRIPT_DIR/update${counter}-sqlite.sql" > last.log 2>&1
+    else
+      $SCRIPT_DIR/update${counter}-sqlite.sh > last.log 2>&1
+    fi
+    # Check if the update was successful
+    ret=$?
+    if [ "$ret" -ne 0 ]; then
+        echo "FAILED (return value $ret)."
+        echo "Error: "$(cat last.log)
+        break # So that ps_dbupdates is updated to its partial update anyway.
+      else
+        echo ok.
+    fi
+    counter=$(($counter+1))
+    updated=1
+  done
+
+  #
+  # save the last update number
+  #
+  if [ $updated -eq 1 ]; then
+    $SQLITE "update $RAS_DBUPDATE set UpdateNumber=$counter where UpdateType='$DB_TYPE'" > last.log 2>&1
+    log "updated database to update $((counter-1))"
+  else
+    log "database already up-to-date, nothing to update."
+  fi
+
 fi
+
+rm -f last.log
 
 #
 # done
 #
 echo
 log "done, exiting."
-exit $CODE_OK
+exit $RC_OK
