ticket:1611 - support for unsigned types in netcdf convertor
Summary: remove use of netcdf_c++ and use the netcdf_c library itself; improve output in systemtest.

Test Plan: run systemtest

Reviewers: bphamhuu, vmerticariu

Reviewed By: bphamhuu

Differential Revision: http://codereview.rasdaman.org/D764

diff --git a/systemtest/run_test.sh.in b/systemtest/run_test.sh.in
--- a/systemtest/run_test.sh.in
+++ b/systemtest/run_test.sh.in
@@ -22,38 +22,48 @@
 # or contact Peter Baumann via <baumann@rasdaman.com>.
 
 if [ $# -ne 1 ]; then
-    echo Usage: $0 "rasdaman_bin_directory.";
-    exit 1;
+    echo "Usage: $0 <rasdaman_bin_directory>"
+    exit 1
 fi
 
 TEST_SEQUENCE=`ls -d @TEST_SEQUENCE@`
-BIN_DIR=$1;
+BIN_DIR=$1
+if [ ! -d "$BIN_DIR" ]; then
+    echo "Directory not found: $BIN_DIR"
+    exit 1
+fi
+if [ ! -f "$BIN_DIR/rasql" ]; then
+    echo "rasql not found: $BIN_DIR/rasql"
+    exit 1
+fi
 
-ret=0;
+PATH=$BIN_DIR:$PATH
+
+log="test.log"
+rm -f "$log"
+
+ret=0
+
 for test_case in $TEST_SEQUENCE; do
-    PATH=$BIN_DIR:$PATH
-    PROG_TEST=$test_case/*.sh;
+    PROG_TEST=($test_case/*.sh)
     echo $PROG_TEST
-    if [ ! -f $test_case/*.sh ]; then
-        continue;
-    fi;
-    echo;
-    echo;
-    $test_case/*.sh;
-    tmp=$?;
-    if [ $tmp -eq 2 ]; then
-        echo $PROG_TEST ... SKIPPED>>logtmp;
-    elif [ $tmp -ne 0 ]; then
-        ret=$tmp;
-        echo $PROG_TEST ... FAIL>>logtmp;
-    else
-        echo $PROG_TEST ... OK>>logtmp;
-    fi;
-        echo "	"see detail in $test_case/test.log>>logtmp;
-done;
+    [ -f $PROG_TEST ] || continue
+    echo
+    echo
 
-echo -e "\n\nTEST SUMMARY\n";
-cat logtmp;
-rm logtmp;
+    SECONDS=0
+    $PROG_TEST
+    rc=$?
+    case $rc in
+        2) status=SKIP;;
+        0) status=OK;;
+        *) status=FAIL; ret=$rc;;
+    esac
+    # print status to output
+    printf "%5s %4ds  $PROG_TEST\n" $status $SECONDS >> "$log"
+done
 
-exit $ret;
+echo -e "\n\nTEST SUMMARY\n"
+cat "$log"
+
+exit $ret
