ticket:698 - Synchronize Petascope demo insertion and add feedback.

diff --git a/applications/petascope/src/main/db/petascope_insertdemo.sh.in b/applications/petascope/src/main/db/petascope_insertdemo.sh.in
--- a/applications/petascope/src/main/db/petascope_insertdemo.sh.in
+++ b/applications/petascope/src/main/db/petascope_insertdemo.sh.in
@@ -121,82 +121,33 @@ check_paths() {
 #
 function import_mst()
 {
- local TESTDATA_PATH="$1"
+  local TESTDATA_PATH="$1"
   if [ ! -f "$TESTDATA_PATH/mean_summer_airtemp.tif" ]; then
     error "testdata file $TESTDATA_PATH/mean_summer_airtemp.tif not found"
   fi
 
   c=$2
-  X=885
-  Y=710
-
   c_colltype='GreySet'
-  c_basetype='char'
-  c_rangetype='unsigned char'
-  c_covtype='RectifiedGridCoverage'
-
+  c_marraytype='GreyImage'
   c_crs='%SECORE_URL%/crs/EPSG/0/4326'
-
-  min_x_geo_coord="111.975"
-  max_y_geo_coord="-8.975"
-  x_res='0.05'
-  y_res='-0.05'
-
-  c_band='value'
 
   #
   # START
   #
+  $RASERASE --coverage $c > /dev/null 2>&1
+  $RASIMPORT -f "${TESTDATA_PATH}/mean_summer_airtemp.tif" \
+             --coll $c \
+             --coverage-name $c \
+             -t  ${c_marraytype}:${c_colltype} \
+             --crs-uri  "$c_crs" \
+             --crs-order 1:0  > /dev/null || exit $RC_ERROR
 
-  $RASQL -q "create collection $c $c_colltype" > /dev/null || exit $RC_ERROR
-  $RASQL -q "insert into $c values ($c_basetype) inv_tiff(\$1)" -f "$TESTDATA_PATH"/mean_summer_airtemp.tif > /dev/null || exit $RC_ERROR
-
-  # general coverage information (name, type, ...)
-  $PSQL -c "INSERT INTO ps_coverage (name, gml_type_id, native_format_id) \
-            VALUES ('$c', (SELECT id FROM ps_gml_subtype WHERE subtype='$c_covtype'), \
-            (SELECT id FROM ps_mime_type WHERE mime_type='application/x-octet-stream'));" > /dev/null || exit $RC_ERROR
-
-  # get the coverage id
-  c_id=$($PSQL -c  "SELECT id FROM ps_coverage WHERE name = '$c' " | head -3 | tail -1) > /dev/null || exit $RC_ERROR
-
-  # get the collection OID (note: take the first OID)
-  c_oid=$($RASQL -q "select oid(m) from $c as m" --out string | grep ' 1:' | awk -F ':' '{print $2}' | tr -d ' \n') > /dev/null || exit $RC_ERROR
-
-  # range set: link the coverage to the rasdaman collection
-  $PSQL -c "INSERT INTO ps_rasdaman_collection (name, oid) VALUES ('$c', $c_oid);" > /dev/null
-  $PSQL -c "INSERT INTO ps_range_set (coverage_id, storage_id) VALUES (\
-              (SELECT id FROM ps_coverage WHERE name='$c'), \
-              (SELECT id FROM ps_rasdaman_collection WHERE name='$c'));" > /dev/null || exit $RC_ERROR
-
-  # describe the datatype of the coverage cell values (range type)
-  # note: assign dimensionless quantity
-  $PSQL -c "INSERT INTO ps_range_type_component (coverage_id, name, component_order, data_type_id, field_id) VALUES (\
-              $c_id, '$c_band', 0, \
-              (SELECT id FROM ps_range_data_type WHERE name='$c_rangetype'), \
-              (SELECT id FROM ps_quantity WHERE label='$c_rangetype' AND description='primitive' LIMIT 1));" > /dev/null || exit $RC_ERROR
-
-  # describe the geo (`index` in this case..) domain
-  $PSQL -c "INSERT INTO ps_crs (uri) SELECT '$c_crs' WHERE NOT EXISTS (SELECT 1 FROM ps_crs WHERE uri='$c_crs');" > /dev/null
-  $PSQL -c "INSERT INTO ps_domain_set (coverage_id, native_crs_ids) \
-            VALUES ($c_id, ARRAY[(SELECT id FROM ps_crs WHERE uri='$c_crs')]);" > /dev/null || exit $RC_ERROR
-  $PSQL -c "INSERT INTO ps_gridded_domain_set (coverage_id, grid_origin) \
-            VALUES ($c_id, '{$max_y_geo_coord, $min_x_geo_coord}');" > /dev/null || exit $RC_ERROR
-  # grid axes:
-  $PSQL -c "INSERT INTO ps_grid_axis (gridded_coverage_id, rasdaman_order) VALUES ($c_id, 0);" > /dev/null || exit $RC_ERROR
-  $PSQL -c "INSERT INTO ps_grid_axis (gridded_coverage_id, rasdaman_order) VALUES ($c_id, 1);" > /dev/null || exit $RC_ERROR
-
-  # offset vectors
-  $PSQL -c "INSERT INTO ps_rectilinear_axis (grid_axis_id, offset_vector) VALUES (\
-              (SELECT id FROM ps_grid_axis WHERE gridded_coverage_id=$c_id AND rasdaman_order=0), \
-              '{0, $x_res}');" > /dev/null || exit $RC_ERROR
-  $PSQL -c "INSERT INTO ps_rectilinear_axis (grid_axis_id, offset_vector) VALUES (\
-              (SELECT id FROM ps_grid_axis WHERE gridded_coverage_id=$c_id AND rasdaman_order=1), \
-              '{$y_res, 0}');" > /dev/null || exit $RC_ERROR
-
-  # initialize WMS
-  "$INITWMS" australia_wms mean_summer_airtemp EPSG:4326 -l '2:4:8:16' -h localhost -p $WCPS_PORT > /dev/null 2>&1
+  # (re)initialize WMS
+  "$DROPWMS" australia_wms > /dev/null 2>&1
+  "$INITWMS" australia_wms mean_summer_airtemp EPSG:4326 -l '2:4:8:16' -h localhost -p $PETASCOPE_PORT > /dev/null 2>&1
   if [ $? -ne 0 ]; then
     log "Warning: WMS initialization for mean_summer_airtemp failed."
+    log "Reloading the server capabilities might have failed (assuming localhost:${PETASCOPE_PORT}): please try to restart the server and check WMS GetCapabilities."
   fi
   "$FILLPYR" mean_summer_airtemp --tasplit > /dev/null 2>&1
   if [ $? -ne 0 ]; then
@@ -254,12 +205,18 @@ RAS_PASS=`grep rasdaman_admin_pass "$SETTINGS" | awk -F "=" '{print $2}' | tr -d
 RAS_DB=`grep rasdaman_database "$SETTINGS" | awk -F "=" '{print $2}' | tr -d '\n'`
 RAS_SERVER=`grep rasdaman_url "$SETTINGS" | awk -F ":|/" '{print $4}' | tr -d '\n'`
 RAS_PORT=`grep rasdaman_url "$SETTINGS" | awk -F ":|/" '{print $5}' | tr -d '\n'`
+PETASCOPE_PORT=8080
 
 #
 # rasdaman commands
 #
 RASQL="@bindir@/rasql --user $RAS_USER --passwd $RAS_PASS -d $RAS_DB -s $RAS_SERVER -p $RAS_PORT"
 RASCONTROL="@bindir@/rascontrol"
+RASIMPORT="@bindir@/rasimport"
+RASERASE="@bindir@/raserase"
+INITWMS="@bindir@/init_wms.sh"
+FILLPYR="@bindir@/fill_pyramid.sh"
+DROPWMS="@bindir@/drop_wms.sh"
 
 # print some info
 log "rasdaman settings"
@@ -273,4 +230,6 @@ check_rasdaman
 #
 # insert sample data to rasdaman
 #
+logn "inserting \`mean_summer_airtemp' 2D demo dataset for WC*S and WMS services... "
 import_mst "$SCRIPT_DIR" mean_summer_airtemp
+echo "Ok."
