Update sequence for table ps_crs in petascope creation query (ticket #289)

diff --git a/applications/petascope/src/main/db/update_petascopedb.sh.in b/applications/petascope/src/main/db/update_petascopedb.sh.in
--- a/applications/petascope/src/main/db/update_petascopedb.sh.in
+++ b/applications/petascope/src/main/db/update_petascopedb.sh.in
@@ -174,6 +174,14 @@ else
 fi
 
 #
+# some updates are written in PL/pgSQL, so install the extension in postgres
+#
+createlang plpgsql $PS_DB > /dev/null
+if [ $? -ne 0 ]; then
+  error "failed creating PL/pgSQL extension in PostgreSQL, please install it first on your system."
+fi
+
+#
 # insert the database updates
 #
 echo
@@ -186,8 +194,10 @@ while [ -f "$SCRIPT_DIR/update$counter.sql" ]; do
 	# Check if the update was successful
 	ret=$?
 	if [ "$ret" -ne 0 ]; then
-		logn " FAILED (return value $ret)."
+		echo "FAILED (return value $ret)."
 		break # So that ps_dbupdates is updated to its partial update anyway.
+  else
+    echo ok.
 	fi
 	counter=$(($counter+1))
 	updated=1
