ticket:502 - fix problem with migration application to load GDAL native library
Summary:
Migration application should invoke the method to load GDAL native library before starting
or later, it will throw exception when using crs projection from GDAL Java library. Also fix migrate_petascopedb.sh script to
get the correct exit code when Java migration application throws exception.

Test Plan: Tested by running migrate_petascopdb.sh from old petascopedb to migrate to new petascopedb.

Reviewers: dmisev

Differential Revision: http://codereview.rasdaman.org/D449

diff --git a/applications/petascope/migrate_petascopedb.sh.in b/applications/petascope/migrate_petascopedb.sh.in
--- a/applications/petascope/migrate_petascopedb.sh.in
+++ b/applications/petascope/migrate_petascopedb.sh.in
@@ -76,7 +76,8 @@ else
     # User can see the log from the terminal at the same time as migration application writes to petascope.log
     # No output log4j, grpc to user's console
     java -jar "$PETASCOPE_MIGRATION_JAR" 2>&1 |  grep -v --line-buffered -e 'grpc' -e 'log4j'
-    if [ "$?" -eq 0 ]; then
+    # NOTE: $? always return 0 even when first command returns 1 (exception in migration application), must get exit code from correct variable.
+    if [ ${PIPESTATUS[0]} -eq 0 ]; then
         log "Migration completted successfully; petascope can be started again."
     else
         error "Migration failed; please check for errors in $LOG_FILE file."
