Fix RPM packaging (ticket #324)

diff --git a/packaging/rpm/rasdaman.init.in b/packaging/rpm/rasdaman.init.in
--- a/packaging/rpm/rasdaman.init.in
+++ b/packaging/rpm/rasdaman.init.in
@@ -19,7 +19,7 @@
 ### END INIT INFO
 
 # Version from spec
-RASVERSION=@RASVERSION@
+RASVERSION=8.4.0
 # RASMAJORVERSION is major version, e.g., 8.0 (this should match RAS_VERSION)
 RASMAJORVERSION=`echo "$RASVERSION" | sed 's/^\([0-9]*\.[0-9]*\).*$/\1/'`
 
@@ -194,16 +194,32 @@ updatedb()
 # Initializes/updates the petascope database
 #
 initpetascopedb(){
-  # create petascope user in postgres
-  $SU -l postgres -c "createuser -SRd tomcat6"
-  RETVAL=$?
-  if [[ $RETVAL != 0 ]]
-  then
-    echo $"creating petascope user in postgres failed"
-    exit $!
+  # determine tomcat user, seems to vary between different distributions
+  tomcat_user=`grep -i tomcat /etc/passwd | awk -F ':' '{ print $1; }' | head -n 1`
+  if [ -z "$tomcat_user" ]; then
+    tomcat_user="tomcat6"
   fi
 
-  $SU -l rasdaman -s "$rasshell" -c "update_petascopedb.sh"
+  # update petascope user in configuration, unless the user has changed it
+  grep 'metadata_user=tomcat6' /etc/rasdaman/petascope.properties > /dev/null
+  if [ $? -ne 0 ]; then
+    sed -i 's/^metadata_user=.\+/metadata_user='$tomcat_user'/' /etc/rasdaman/petascope.properties
+  fi
+
+  # create petascope user in postgres if it isn't already created
+  $SU -l postgres -s "$rasshell" -c "psql -c 'SELECT * FROM pg_user'" | grep "$tomcat_user" > /dev/null
+  if [ $? -ne 0 ]; then
+    echo creating user
+    $SU -l postgres -c "createuser -SRd $tomcat_user"
+    RETVAL=$?
+    if [[ $RETVAL != 0 ]]
+    then
+      echo $"creating petascope user in postgres failed"
+      exit $!
+    fi
+  fi
+
+  $SU -l $tomcat_user -s "$rasshell" -c "update_petascopedb.sh"
 }
 
 #
@@ -219,7 +235,7 @@ dropdb(){
     exit $!
   fi
   echo dropping user...
-  $SU -l postgres -c "dropuser rasdaman"
+  $SU -l postgres -s "$rasshell" -c "dropuser rasdaman"
   RETVAL=$?
   if [[ $RETVAL != 0 ]]
   then
@@ -233,7 +249,7 @@ dropdb(){
 #
 droppetascopedb(){
   echo dropping petascopedb...
-  $SU -l rasdaman -s "$rasshell" -c "dropdb petascopedb"
+  $SU -l postgres -s "$rasshell" -c "dropdb petascopedb"
   RETVAL=$?
   if [[ $RETVAL != 0 ]]
   then
@@ -284,7 +300,9 @@ case "$1" in
   droppetascopedb
   ;;
   *)
-  echo $"Usage: $prog {start|stop|restart|condrestart|status|initdb|updatedb|dropdb|initpetascopedb|updatepetascopedb|droppetascopedb}"
+  echo $"Usage: $prog {start|stop|restart|condrestart|status|"
+  echo $"                 initdb|updatedb|dropdb|"
+  echo $"                 initpetascopedb|updatepetascopedb|droppetascopedb}"
   RETVAL=3
 esac
 
