ticket:000 - update RPM spec and init script for 9.0

diff --git a/packaging/rpm/rasdaman.init.in b/packaging/rpm/rasdaman.init.in
--- a/packaging/rpm/rasdaman.init.in
+++ b/packaging/rpm/rasdaman.init.in
@@ -19,7 +19,7 @@
 ### END INIT INFO
 
 # Version from spec
-RASVERSION=8.4.0
+RASVERSION=9.0.0
 # RASMAJORVERSION is major version, e.g., 8.0 (this should match RAS_VERSION)
 RASMAJORVERSION=`echo "$RASVERSION" | sed 's/^\([0-9]*\.[0-9]*\).*$/\1/'`
 
@@ -65,11 +65,67 @@ raslog=$rasdir/startup.log
 rascontrol="RASLOGIN=$raslogin $rasctrl"
 deffile=$rasdir/basictypes.dl
 
+# check if the rasdaman system user exists
+check_rasdaman_user()
+{
+  getent passwd rasdaman > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    echo $"rasdaman user not found, please reinstall rasdaman."
+    exit $!
+  fi
+}
+
+create_rasdaman_role()
+{
+  $SU -l postgres -c "psql postgres -tAc \"SELECT 1 FROM pg_roles WHERE rolname='rasdaman'\" | grep -q 1 || createuser -s rasdaman"
+  RETVAL=$?
+  if [[ $RETVAL != 0 ]]
+  then
+    echo $"creating rasdaman user in postgres failed."
+    exit $!
+  fi
+}
+
+create_petascope_role()
+{
+  $SU -l postgres -c "psql postgres -tAc \"SELECT 1 FROM pg_roles WHERE rolname='petauser'\" | grep -q 1"
+  RETVAL=$?
+  if [[ $RETVAL != 0 ]]
+  then
+    $SU -l postgres -c "createuser -s petauser"
+    RETVAL=$?
+    if [[ $RETVAL != 0 ]]
+    then
+      echo $"creating petascope user in postgres failed."
+      exit $!
+    fi
+    $SU -l postgres -c "psql -c \"alter user petauser with password 'petapasswd'\""
+    RETVAL=$?
+    if [[ $RETVAL != 0 ]]
+    then
+      echo $"updating petascope user password in postgres failed."
+      exit $!
+    fi
+  fi
+}
+
+# check if postgres is running
+check_postgres_running()
+{
+  service postgresql status > /dev/null 2>&1
+  if [ $? -eq 3 ]; then
+    echo $"please start PostgreSQL first with 'service postgresql start'."
+    exit $!
+  fi
+}
+
 # The semantics of these two functions differ from the way apachectl does
 # things -- attempting to start while running is a failure, and shutdown
 # when not running is also a failure.  So we just do it the way init scripts
 # are expected to behave here.
 start() {
+  check_rasdaman_user
+
   chown -R rasdaman:rasdaman "$raslogdir"
   # Make sure startup-time log file is valid
   if [ ! -e "$raslog" -a ! -h "$raslog" ]
@@ -80,45 +136,52 @@ start() {
     [ -x /usr/bin/chcon ] && /usr/bin/chcon -u system_u -r object_r -t postgresql_log_t "$raslog" 2>/dev/null
   fi
 
-  # Check for the PGDATA structure
-  #if [ -f "$PGDATA/PG_VERSION" ] && [ -d "$PGDATA/base" ]
-  #then
-  #  echo
-  #  echo $"PostgreSQL database was found."
-  #  echo $"Version is not checked here."
-  #  echo $"Location $PGDATA."
-  #else
-  #  # No existing PGDATA! Warn the user to initdb it.
-  #  echo
-  #  echo "$PGDATA is missing. Use \"service rasmgr initdb\" to initialize the cluster first."
-  #  echo "PostgreSQL database will be initialized automatically."
-  #  echo_failure
-  #  echo
-  #  exit 1
-  #fi
+  check_postgres_running
 
-  echo -n $"Starting $prog: "
+  # check if RASBASE is initialized
+  $SU -l rasdaman -s "$rasshell" -c "psql --list | grep RASBASE" > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    echo $"RASBASE not found, please run 'service rasdaman initdb' first."
+    exit $!
+  fi
+
+  echo $"Starting $prog..."
+  echo -n $"Starting $rasmgr: "
   $SU -l rasdaman -s "$rasshell" -c "$rasmgr &" >> "$raslog" 2>&1 < /dev/null
   RETVAL=$?
   if [[ $RETVAL = 0 ]]
   then
-    echo
+    echo ok.
     touch ${lockfile}
     pidof -s "$rasmgr" > ${pidfile}
+  else
+    echo $"failed starting rasmgr, please see $raslog for more details"
+    exit $!
   fi
 
   sleep $wait_for_children
 
   for SRV in $servers
   do
-    echo $"$rasctrl: starting server $SRV..."
+    echo -n $"$rasctrl: starting server $SRV... "
     $SU -l rasdaman -s "$rasshell" -c "$rascontrol -e -q -x up srv $SRV" >> "$raslog" 2>&1 < /dev/null
     RETVAL=$?
     if [[ $RETVAL != 0 ]]
     then
+      echo $"failed starting a rasserver, please see $raslog for more details"
       exit $!
+    else
+      echo $"ok."
     fi
   done
+
+  $SU -l rasdaman -s "$rasshell" -c "rasql -q 'select c from RAS_COLLECTIONNAMES AS c' --out string" > /dev/null 2>&1
+  RETVAL=$?
+  if [[ $RETVAL != 0 ]]
+  then
+    echo $"failed starting rasdaman, simple query check failed."
+    exit $!
+  fi
 
   return $RETVAL
 }
@@ -127,18 +190,33 @@ start() {
 # httpd parent; this gives enough time for the httpd parent to SIGKILL any
 # errant children.
 stop() {
+  check_rasdaman_user
+
   running=`$SU -l rasdaman -s "$rasshell" -c "$rascontrol -e -q -x list srv | awk '{ if (\\$6 == \"UP\") print \\$2;}'"`
   for SRV in $running
   do
-    echo $"$rasctrl: stoping server $SRV..."
+    echo -n $"$rasctrl: stoping server $SRV... "
     $SU -l rasdaman -s "$rasshell" -c "$rascontrol -e -q -x down srv $SRV -kill" >> "$raslog" 2>&1 < /dev/null
+    RETVAL=$?
+    if [[ $RETVAL != 0 ]]
+    then
+      echo $"failed, see $raslog for details."
+    else
+      echo $"ok."
+    fi
   done
 
   sleep $wait_for_children
 
+  echo -n $"$rasctrl: stoping rasmgr... "
   $SU -l rasdaman -s "$rasshell" -c "$rascontrol -e -q -x down host -all" >> "$raslog" 2>&1 < /dev/null
-
   RETVAL=$?
+  if [[ $RETVAL != 0 ]]
+  then
+    echo $"failed, see $raslog for details."
+  else
+    echo $"ok."
+  fi
 
   [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
 }
@@ -147,28 +225,21 @@ stop() {
 # Initializes RASBASE
 #
 initdb(){
-  bhostname=`hostname`
-  mv /etc/rasdaman/rasmgr.conf /etc/rasdaman/rasmgr.conf.init
+  check_postgres_running
+
+  bhostname=$(hostname)
+  cp /etc/rasdaman/rasmgr.conf /etc/rasdaman/rasmgr.conf.init
   cat /etc/rasdaman/rasmgr.conf.init | sed -e "s/ -host [^ ]*/ -host $bhostname/g" > /etc/rasdaman/rasmgr.conf
 
-  service postgresql initdb
-  service postgresql start
-
   # create rasdaman user in postgres
-  $SU -l postgres -c "createuser -d -r -S rasdaman"
-  RETVAL=$?
-  if [[ $RETVAL != 0 ]]
-  then
-    echo $"creating rasdaman user in postgres failed"
-    exit $!
-  fi
+  create_rasdaman_role
 
   # create database
   $SU -l rasdaman -s "$rasshell" -c "createdb RASBASE"
   RETVAL=$?
   if [[ $RETVAL != 0 ]]
   then
-    echo $"creating RASBASE in postgres failed"
+    echo $"creating RASBASE in postgres failed."
     exit $!
   fi
 
@@ -177,7 +248,7 @@ initdb(){
   RETVAL=$?
   if [[ $RETVAL != 0 ]]
   then
-    echo $"inserting type definitions to rasdaman with rasdl failed"
+    echo $"inserting type definitions to rasdaman with rasdl failed."
     exit $!
   fi
 }
@@ -187,6 +258,8 @@ initdb(){
 #
 updatedb()
 {
+  check_rasdaman_user
+
   $SU -l rasdaman -s "$rasshell" -c "update_db.sh"
 }
 
@@ -194,45 +267,55 @@ updatedb()
 # Initializes/updates the petascope database
 #
 initpetascopedb(){
-  # determine tomcat user, seems to vary between different distributions
-  tomcat_user=`grep -i tomcat /etc/passwd | awk -F ':' '{ print $1; }' | head -n 1`
-  if [ -z "$tomcat_user" ]; then
-    tomcat_user="tomcat6"
-  fi
+  check_rasdaman_user
+  check_postgres_running
 
   # update petascope user in configuration, unless the user has changed it
-  grep 'metadata_user=tomcat6' /etc/rasdaman/petascope.properties > /dev/null
+  grep 'metadata_user=inituser' /etc/rasdaman/petascope.properties > /dev/null
   if [ $? -eq 0 ]; then
-    sed -i 's/^metadata_user=.\+/metadata_user='$tomcat_user'/' /etc/rasdaman/petascope.properties
-  fi
+    sed -i 's/^metadata_user=.\+/metadata_user=petauser/' /etc/rasdaman/petascope.properties
+    sed -i 's/^metadata_pass=.\+/metadata_user=petapasswd/' /etc/rasdaman/petascope.properties
 
-  # create petascope user in postgres if it isn't already created
-  $SU -l postgres -s "$rasshell" -c "psql -c 'SELECT * FROM pg_user'" | grep "$tomcat_user" > /dev/null
-  if [ $? -ne 0 ]; then
-    echo creating user
-    $SU -l postgres -c "createuser -SRd $tomcat_user"
-    RETVAL=$?
-    if [[ $RETVAL != 0 ]]
-    then
-      echo $"creating petascope user in postgres failed"
-      exit $!
+    # setup postgres to allow connections from petascope
+    grep trust $PGDATA/pg_hba.conf | grep -v METHOD > /dev/null
+    if [ $? -ne 0 ]; then
+      echo $"adding trust authentication to $PGDATA/pg_hba.conf"
+      cp $PGDATA/pg_hba.conf $PGDATA/pg_hba.conf.bak
+cat << EOF > $PGDATA/pg_hba.conf
+# TYPE  DATABASE    USER        CIDR-ADDRESS          METHOD
+
+# "local" is for Unix domain socket connections only
+#------------------------------------------------------------
+local   all         all                               trust
+# IPv4 local connections:
+host    all         all         127.0.0.1/32          trust
+# IPv6 local connections:
+host    all         all         ::1/128               trust
+#------------------------------------------------------------
+EOF
+
+      sed '1,/# TYPE/d' $PGDATA/pg_hba.conf.bak >> $PGDATA/pg_hba.conf
     fi
   fi
 
-  $SU -l $tomcat_user -s "$rasshell" -c "update_petascopedb.sh"
+  # create petascope user in postgres if it isn't already created
+  create_petascope_role
+
+  $SU -l rasdaman -s "$rasshell" -c "update_petascopedb.sh"
 }
 
 #
 # Drop RASBASE
 #
 dropdb(){
+  check_rasdaman_user
+
   echo dropping RASBASE...
   $SU -l rasdaman -s "$rasshell" -c "dropdb RASBASE"
   RETVAL=$?
   if [[ $RETVAL != 0 ]]
   then
     echo $"dropdb failed"
-    exit $!
   fi
   echo dropping user...
   $SU -l postgres -s "$rasshell" -c "dropuser rasdaman"
@@ -240,7 +323,6 @@ dropdb(){
   if [[ $RETVAL != 0 ]]
   then
     echo $"drop user failed"
-    exit $!
   fi
 }
 
@@ -248,13 +330,14 @@ dropdb(){
 # Drop the petascope database
 #
 droppetascopedb(){
+  check_rasdaman_user
+
   echo dropping petascopedb...
   $SU -l postgres -s "$rasshell" -c "dropdb petascopedb"
   RETVAL=$?
   if [[ $RETVAL != 0 ]]
   then
-    echo $"dropdb failed"
-    exit $!
+    echo $"droppetascopedb failed"
   fi
 }
 
