ticket:2290 - remove rview from docs, ticket:2291 - all executable programs to output version nunmber

diff --git a/applications/petascope/coverages_example/petascope_insertdemo.sh.in b/applications/petascope/coverages_example/petascope_insertdemo.sh.in
--- a/applications/petascope/coverages_example/petascope_insertdemo.sh.in
+++ b/applications/petascope/coverages_example/petascope_insertdemo.sh.in
@@ -34,19 +34,20 @@
 #  2) etc/petascope.properties should be present, and the metadata_user should
 #     have appropriate write rights in postgres.
 
-PROG=`basename $0`
+PROG=$(basename "$0")
 
-CODE_OK=0
-CODE_FAIL=255
+VERSION="@VERSION_FULL@"
 
-# petascope settings file
 SETTINGS="@sysconfdir@/petascope.properties"
-
+WCST_IMPORT="@bindir@/wcst_import.sh"
 # petascope updateN.sql scripts and demo examples
 SCRIPT_DIR="@pkgdatadir@/petascope"
-
 # input file directory (coverage files + recipe files .template.json)
 DATA_DIRECTORY=$SCRIPT_DIR/petascope_insertdemo_data
+DEFAULT_SERVICE_ENDPOINT="http://localhost:8080"
+
+RC_OK=0
+RC_ERROR=1
 
 # ------------------------------------------------------------------------------
 # functions
@@ -55,48 +56,26 @@ DATA_DIRECTORY=$SCRIPT_DIR/petascope_insertdemo_data
 #
 # logging
 #
-log() {
-  echo "$PROG: $*"
-}
-logn() {
-  echo -n "$PROG: $*"
-}
-error() {
-  echo "$PROG: $*" >&2
-  echo "$PROG: exiting." >&2
-  exit $CODE_FAIL
-}
-
-
+log()  { echo "$PROG: $*"; }
+logn() { printf "%s" "$PROG: $*"; }
+error(){ echo "$PROG: $*" >&2; exit $RC_ERROR; }
+check(){ [ $? ] && echo "ok." || echo "failed."; }
 
 usage()
 {
-  local usage="
+cat <<EOF
   Usage: $PROG [OPTION]...
 
   Description:
-    Inserts sample demo data into petascope.
+    Insert sample demo data into rasdaman.
 
   Options:
+    -s, --service-endpoint
+     specify the service endpoint (default: $DEFAULT_SERVICE_ENDPOINT)
     -h, --help
      display this help and exit
-    -s, --service-endpoint
-     specify the service endpoint (default: http://localhost:8080)
-  "
-
-  echo "$usage"
+EOF
   exit $RC_OK
-}
-
-# Read the property of a value by input key from input properties file
-get_property_value()
-{
-    # $1 is path to input properties file (e.g: /opt/rasdaman/etc/petascope.properties).
-    # $2 is the key of a property in this file which needs to get the value of this key.
-    local properties_file="$1"
-    local key="$2"
-    # only grep key=value line not commented line (e.g: #key=value)
-    grep "^$key=" "$properties_file" | sed -e 's/.*=//' -e 's/^[ \t]*//'
 }
 
 #
@@ -104,22 +83,15 @@ get_property_value()
 #
 import_all_coverages()
 {
-  log "Starting to ingest example coverages to petascope..."
-  for DATA in $DATA_DIRECTORY/*; do
+  log "importing sample coverages into rasdaman $VERSION..."
+  log "petascope service endpoint: $PETASCOPE_URL"
+  log "secore service endpoint: $SECORE_URL"
 
-    # 1.1 Get the recipe file template
-    RECIPE_TEMPLATE_FILE=$(find $DATA -type f -name "*.template.json")
-
-    # 1.2 Get the coverage id from recipe file
-    COVERAGE_ID=$(grep -Po '"coverage_id":.*?[^\\]",' $RECIPE_TEMPLATE_FILE | awk -F'"' '{print $4}')
-
-    # 1.3 Import coverage_id
-    import_coverage $COVERAGE_ID $DATA $RECIPE_TEMPLATE_FILE
+  for DATA in "$DATA_DIRECTORY"/*; do
+    RECIPE_TEMPLATE_FILE=$(find "$DATA" -type f -name "*.template.json")
+    COVERAGE_ID=$(grep -Po '"coverage_id":.*?[^\\]",' "$RECIPE_TEMPLATE_FILE" | awk -F'"' '{print $4}')
+    import_coverage "$COVERAGE_ID" "$DATA" "$RECIPE_TEMPLATE_FILE"
   done
-
-  log "All coverages are imported correctly. Done."
-  log "Ok."
-  exit $CODE_OK
 }
 
 #
@@ -130,32 +102,18 @@ import_coverage()
   COVERAGE_ID="$1"
   DATA_FOLDER_PATH="$2" # coverage directory
   RECIPE_TEMPLATE_FILE="$3"
-
-  # START
-
-  # 1. Insert coverage by WCS
-
-  # 1.1 Copy file from template.json to ingest.json
   RECIPE_FILE="/tmp/ingest.json"
-  cp "$RECIPE_TEMPLATE_FILE" "$RECIPE_FILE"
 
-  sed -i "s|DATA_FOLDER_PATH|$DATA_FOLDER_PATH|g" "$RECIPE_FILE"
+  sed -e "s|DATA_FOLDER_PATH|$DATA_FOLDER_PATH|g" \
+      -e "s|PETASCOPE_URL|$PETASCOPE_URL|g" \
+      -e "s|SECORE_URL|$SECORE_URL|g" \
+      "$RECIPE_TEMPLATE_FILE" > "$RECIPE_FILE"
 
-  # 1.2 Replace PETASCOPE_URL and SECORE_URL in petascope_insertdemo.template.json
-  sed -i "s|PETASCOPE_URL|$PETASCOPE_URL|g" "$RECIPE_FILE"
-  sed -i "s|SECORE_URL|$SECORE_URL|g" "$RECIPE_FILE"
+  logn "  importing coverage $COVERAGE_ID (detail output in /tmp/$COVERAGE_ID.log)... "
+  "$WCST_IMPORT" "$RECIPE_FILE" > "/tmp/$COVERAGE_ID.log" 2>&1
+  check
 
-  # 1.3 Run wcst_import with petascope_insertdemo.json recipe
-  logn "Ingesting $COVERAGE_ID to petascope by wcst_import..."
-  "@bindir@/wcst_import.sh" $RECIPE_FILE
-  echo "Done."
-
-  # 1.4 Remove tmp $RECIPE_FILE
-  logn "Cleaning temporary file..."
-  if [ -f "$RECIPE_FILE" ]; then
-     rm "$RECIPE_FILE"
-  fi
-  echo "Done."
+  rm -f "$RECIPE_FILE"
 }
 
 # ------------------------------------------------------------------------------
@@ -170,38 +128,31 @@ import_coverage()
 # ----------------------------------------------------------------------------
 # parse command-line options
 # ----------------------------------------------------------------------------
-SERVICE_ENDPOINT=http://localhost:8080
 
-SECORE_URL=$(get_property_value "$SETTINGS" "secore_urls")
-
-if [ -n "$SECORE_URL" ]; then
-  SECORE_URL=$SERVICE_ENDPOINT/def
-fi
-
+SERVICE_ENDPOINT="$DEFAULT_SERVICE_ENDPOINT"
 option=
 for i in "$@"; do
   if [ -n "$option" ]; then
     case $option in
-      -s|--service-endpoint*)
-        SERVICE_ENDPOINT="$i";;
-      *) error "unknown option: $option";;
+      -s|--service-endpoint*) SERVICE_ENDPOINT="$i";;
+      *)                      error "unknown option: $option";;
     esac
     option=""
   else
     option=""
     case $i in
-      -h|--help*)     usage;;
-      *)              option="$i";;
+      -h|--help*) usage;;
+      *)          option="$i";;
     esac
   fi
 done
 
-# petascope, secore URL
-PETASCOPE_URL=$SERVICE_ENDPOINT/rasdaman/ows
+PETASCOPE_URL="$SERVICE_ENDPOINT/rasdaman/ows"
 
-log "Petascope service endpoint is: "$PETASCOPE_URL
-log "Secore service endpoint is: "$SECORE_URL
-
-echo -e
+SECORE_URL=$(grep "^secore_urls=" "$SETTINGS" | sed -e 's/.*=//' -e 's/^[ \t]*//')
+[ -z "$SECORE_URL" ] && SECORE_URL="$SERVICE_ENDPOINT/def"
 
 import_all_coverages
+
+log "done."
+exit $RC_OK
diff --git a/applications/wcst_import/wcst_import.sh.in b/applications/wcst_import/wcst_import.sh.in
--- a/applications/wcst_import/wcst_import.sh.in
+++ b/applications/wcst_import/wcst_import.sh.in
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 # *
 # * This file is part of rasdaman community.
 # *
@@ -15,67 +15,77 @@
 # * You should have received a copy of the GNU  General Public License
 # * along with rasdaman community.  If not, see <http://www.gnu.org/licenses/>.
 # *
-# * Copyright 2003 - 2019 Peter Baumann / rasdaman GmbH.
+# * Copyright 2003 - 2020 Peter Baumann / rasdaman GmbH.
 # *
 # * For more information please see <http://www.rasdaman.org>
 # * or contact Peter Baumann via <baumann@rasdaman.com>.
 # *
-#
-# Call the wcst_import.py from the share directory
+
+PROG=$(basename "$0")
+
+VERSION="@VERSION_FULL@"
+WCST_IMPORT_PY_SCRIPT="@WCST_IMPORT_PY_SCRIPT@"
+WCST_IMPORT_DAEMON_PY_SCRIPT="@WCST_IMPORT_DAEMON_PY_SCRIPT@"
+# env variable used by session.py
 export PETASCOPE_PROPERTIES_PATH="@CONF_DIR@/petascope.properties"
 
 RC_OK=0
+RC_ERROR=1
 
 daemon_flag=false
 watch_flag=false
-
 watch_interval=3600
-
 user=""
 passwd=""
 identity_file_path=""
 
+# logging
+log()  { echo "$PROG: $*"; }
+logn() { printf "%s" "$PROG: $*"; }
+error(){ echo "$PROG: $*" >&2; exit $RC_ERROR; }
+
 # check if optional arguments are not empty then concatenate them
-add_args() {
+add_args()
+{
     arg_key="$1"
     arg_val="$2"
     # e.g: argv_val="stop", arg="-d"
 
-    if [[ ! -z "$arg_val" ]]; then
+    if [ -n "$arg_val" ]; then
         wcst_import_py_args="$wcst_import_py_args $arg_key $arg_val"
     fi
 }
 
+# print optional error, and usage directions
 usage()
 {
-  local usage="
+  [ -n "$1" ] && echo "$PROG: $*"
+  cat <<EOF
+
 Usage: $PROG [OPTION] <ingredients_file>
 
-wcst_import.sh is a tool for importing data into petascope via WCS-T (example: http://rasdaman.org/wiki/WCSTImportGuide).
+wcst_import.sh is a tool for importing data into petascope via WCS-T.
 
 Options:
+  -d, --daemon <command>
+    run as daemon; <command> must be one of start, stop, status, or restart.
+  -w, --watch [ <interval> ]
+    the daemon (-d) waits for <interval> seconds before checking the ingredients 
+    file for new data; by default the interval is 3600 (1 hour).
+  -i, --identity-file
+    specify a file from which credentials of a valid petascope user are read;
+    the credentials must be specified in the file as username:password
+  -u, --user <username>
+    specify a valid user for the petascope endpoint; the password will be
+    asked interactively by wcst_import.sh
   -q, --quiet
     suppress regular output
+  --version
+    print version
   -h, --help
     display this help and exit
-  -d, --daemon
-    run wcst_import.sh as daemon
-    usage: -d|--daemon start|stop|status|restart
-  -w, --watch [interval (seconds)]
-    the daemon waits for [interval] seconds before checking the ingredients file for new data
-    [interval] must be a positive number; by default the interval is 3600 (1 hour)
+EOF
 
-    usage: wcst_import <ingredients_file> --daemon start|restart --watch [interval]
-"
-
-   local -r usage="$usage
-  -i, --identity-file
-    selects a file from which the identity (username:password) of an user with qualified priviledges of the petascope endpoint is read
-  -u, --user USER_NAME
-    input identity of username and password of an user with qualified priviledges of the petascope endpoint in interactive mode
-"
-
-  echo "$usage"
   exit $RC_OK
 }
 
@@ -85,98 +95,79 @@ Options:
 quiet=false 
 while [ "$1" != "" ]; do
     case $1 in
-      -h|--help)     usage;;
-      -q|--quiet)   quiet=true;;
-      -d|--daemon)
-        daemon_flag=true
-        shift
-        daemon_action="$1";;
-      -w|--watch)
-        watch_flag=true
-        shift
-        watch_interval=$1;;
-
-      -i|--identity-file)
-        # Credentials stored in a text file (username:password)
-        shift
-        identity_file_path=$(readlink -f "$1");;
-      -u|--user)
-        shift
-        # Interactive mode, input password afterwards
-        user="$1";;
-
-      *) ingredients_file=$(readlink -f "$1");;
+      -h|--help)          usage;;
+      -q|--quiet)         quiet=true;;
+      -d|--daemon)        shift; daemon_flag=true; daemon_action="$1";;
+      -w|--watch)         shift; watch_flag=true; watch_interval=$1;;
+      -i|--identity-file) shift; identity_file_path=$(readlink -f "$1");;
+      -u|--user)          shift; user="$1";;
+      --version)          echo "$PROG $VERSION"; exit $RC_OK;;
+      *)                  ingredients_file=$(readlink -f "$1");;
     esac
     shift
 done
 
-if [[ "$ingredients_file" == "" ]]; then
-  usage
-fi
+[ "$ingredients_file" = "" ] && usage "no ingredients file specified."
 
-if ! [[ $watch_interval =~ ^[\0-9]*\.?[0-9]+$  && (( watch_interval > 0)) ]]; then
-  usage
-fi
+case $watch_interval in
+    ''|*[!0-9]*) usage "invalid watch interval specified: $watch_interval";;
+    *)           [ "$watch_interval" -gt 0 ] || usage "please specify a positive watch interval.";;
+esac
 
-if [[ "$watch_flag" == true && "$daemon_flag" == false ]]; then
+if [ "$watch_flag" = true ] && [ "$daemon_flag" = false ]; then
   daemon_action='start'
   daemon_flag=true
 fi
 
 # check if the daemon is active for this ingredients_file
-if ps aux | grep -E -v "grep|wcst_import.sh" | grep python | grep $ingredients_file > /dev/null
-then
+if ps aux | grep -E -v "grep|wcst_import.sh" | grep python | grep "$ingredients_file" > /dev/null; then
   daemon_is_active=true
 else
   daemon_is_active=false
 fi
 
-# Do not allow gdal to create auxiliary file as it can have no permission to do it in input data folders
+# Prevent gdal from creating auxiliary files as it may not have permissions in data folders
 export GDAL_PAM_ENABLED=NO
 
-script=@WCST_IMPORT_DAEMON_PY_SCRIPT@
-if [[ "$daemon_flag" == false ]]; then
-  if [[ "$daemon_is_active" == true ]]; then
-    echo "A working or daemon instance for this ingredients file is already running; please stop it first."
-    echo "In case of daemon, usage: -d|--daemon stop"
+if [ "$daemon_flag" = false ]; then
+  if [ "$daemon_is_active" = true ]; then
+    echo "$PROG: an instance for this ingredients file is already running, please stop it first; in case of daemon use --daemon stop"
     exit $RC_OK
   fi
-  script=@WCST_IMPORT_PY_SCRIPT@
+  script="$WCST_IMPORT_PY_SCRIPT"
+else
+  script="$WCST_IMPORT_DAEMON_PY_SCRIPT"
 fi
 
-
-if [[ ! -z "$user" ]]; then
-    echo "Please type password for user '$user':"
-    read -s passwd
-elif [[ ! -z "$identity_file_path" ]]; then
-    if [[ ! -f "$identity_file_path" ]]; then
-        echo "Identity file '$identity_file_path' does not exist"
-        exit $RC_ERROR
+if [ -n "$user" ]; then
+    echo "$PROG: please type password for user '$user':"
+    stty_orig=$(stty -g)
+    stty -echo
+    read -r passwd
+    stty "$stty_orig"
+elif [ -n "$identity_file_path" ]; then
+    if [ ! -f "$identity_file_path" ]; then
+        error "identity file '$identity_file_path' does not exist"
     fi
-    if [[ ! -r "$identity_file_path" ]]; then
-        echo "Identity file '$identity_file_path' cannot be read"
-        exit $RC_ERROR
+    if [ ! -r "$identity_file_path" ]; then
+        error "identity file '$identity_file_path' cannot be read"
     fi
 
     user=$(awk -F: '{ print $1 }' "$identity_file_path")
     passwd=$(awk -F: '{ print $2 }' "$identity_file_path")
-
-    if [ -z "$user" -o -z "$passwd" ]; then
-        echo "Cannot parse username or password from the identity file '$identity_file_path'. The format must be username:password."
-        exit $RC_ERROR
+    if [ -z "$user" ] || [ -z "$passwd" ]; then
+        error "cannot parse username or password from the identity file '$identity_file_path'; expected format username:password."
     fi
 fi
 
 wcst_import_py_args="python3 $script -i $ingredients_file"
 add_args "-d" "$daemon_action"
-if [[ "$daemon_flag" == true ]]; then
-    add_args "-w" "$watch_interval"
-fi
+[ "$daemon_flag" = true ] && add_args "-w" "$watch_interval"
 add_args "--user" "$user"
 add_args "--passwd" "$passwd"
 
-if [[ "$quiet" == true ]]; then
-    eval "$wcst_import_py_args" 2>&1 > /dev/null
+if [ "$quiet" = true ]; then
+    eval "$wcst_import_py_args" > /dev/null 2>&1
 else
     eval "$wcst_import_py_args"
 fi
diff --git a/bin/create_db.sh.in b/bin/create_db.sh.in
--- a/bin/create_db.sh.in
+++ b/bin/create_db.sh.in
@@ -32,9 +32,9 @@
 # --- constants & routines
 
 # script name
-PROG=$(basename $0)
+PROG=$(basename "$0")
 
-VERSION=@RMANVERSION@
+VERSION="@VERSION_FULL@"
 
 # script return codes
 RC_OK=0
@@ -54,9 +54,9 @@ DATABASE_NAME=RASBASE
 
 DBCONN="@dbconn@"
 
-log()  { echo "$PROG: $@"; }
-logn() { echo -n "$PROG: $@"; }
-error(){ echo "$PROG: $@" >&2; exit $RC_ERROR; }
+log()  { echo "$PROG: $*"; }
+logn() { printf "%s" "$PROG: $*"; }
+error(){ echo "$PROG: $*" >&2; exit $RC_ERROR; }
 check(){ [ $? ] && echo "ok." || echo "failed."; }
 
 execute_query() {
@@ -64,13 +64,13 @@ execute_query() {
     error "failed executing query: $1"
 }
 
-log "creating database, rasdaman v$VERSION on base DBMS $BASEDBMS"
+log "creating database, rasdaman $VERSION on base DBMS $BASEDBMS"
 
 # --- checking preconditions
 
 # - Can I find utilities?
 if [ "$BASEDBMS" = "$BASEDBMS_PGSQL" ]; then
-    psql --help 2>&1 1>/dev/null || \
+    psql --help 1>/dev/null 2>&1 || \
         error "Error: cannot find psql - PostgreSQL not installed or PATH variable does not contain PostgreSQL path?"
 fi
 
diff --git a/bin/update_db.sh.in b/bin/update_db.sh.in
--- a/bin/update_db.sh.in
+++ b/bin/update_db.sh.in
@@ -39,7 +39,9 @@
 #  2) User running the script must have write access in PostgreSQL
 #  3) share/rasdaman/db_updates should contain the SQL update scripts
 
-PROG=$(basename $0)
+PROG=$(basename "$0")
+
+VERSION="@VERSION_FULL@"
 
 export RC_OK=0
 export RC_ERROR=255
@@ -64,15 +66,17 @@ export DBCONN=@dbconn@
 #
 # logging
 #
-log()  { echo "$PROG: $@"; }
-logn() { echo -n "$PROG: $@"; }
-error(){ echo "$PROG: $@" >&2; exit $RC_ERROR; }
-check(){ [ $? -eq 0 ] && echo "ok." || echo "failed."; }
+log()  { echo "$PROG: $*"; }
+logn() { printf "%s" "$PROG: $*"; }
+error(){ echo "$PROG: $*" >&2; exit $RC_ERROR; }
+check(){ [ $? ] && echo "ok." || echo "failed."; }
 checkerr() { [ $? -eq 0 ] && echo "ok." || error "failed, exiting."; }
 
 #
 # checks
 #
+
+log "upgrading database schema of rasdaman $VERSION"
 
 if [ ! -d "$SCRIPT_DIR" ]; then
   error "SQL update script directory not found: $SCRIPT_DIR"
@@ -135,10 +139,9 @@ if [ "$BASEDBMS" = "$BASEDBMS_PGSQL" ]; then
   #
   # insert the database updates
   #
-  echo
-  log "executing updates:"
   updated=0
   while [ -f "$SCRIPT_DIR/update$counter.sql" ]; do
+    [ $updated -eq 0 ] && log "executing updates:"
     logn "  update $counter... "
           # Note for future .sql files: do not add manual BEGIN/COMMIT transactions, they are handled by psql
     $PSQL --set ON_ERROR_STOP=on --single-transaction -f "$SCRIPT_DIR/update$counter.sql" > "$last_log" 2>&1
@@ -195,8 +198,6 @@ else
   #
   # insert the database updates
   #
-  echo
-  log "executing updates:"
   updated=0
   while [ -f "$SCRIPT_DIR/update${counter}-sqlite.sql" -o -f "$SCRIPT_DIR/update${counter}-sqlite.sh" ]; do
 
@@ -209,6 +210,7 @@ else
       checkerr
     fi
 
+    [ $updated -eq 0 ] && log "executing updates:"
     logn "  update $counter... "
     if [ -f "$SCRIPT_DIR/update${counter}-sqlite.sh" ]; then
       sh "$SCRIPT_DIR/update${counter}-sqlite.sh"
@@ -233,7 +235,7 @@ else
     $SQLITE "update $RAS_DBUPDATE set UpdateNumber=$counter where UpdateType='$DB_TYPE'" > "$last_log" 2>&1
     log "updated database to update $((counter-1))"
   else
-    log "database already up-to-date, nothing to update."
+    log "database already up-to-date."
   fi
 
 fi
@@ -243,6 +245,5 @@ rm -f "$last_log"
 #
 # done
 #
-echo
-log "done, exiting."
+log "done."
 exit $RC_OK
